//! Deterministic TypeScript and JSON fixtures for `@ployz/sdk` public payloads.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use serde::de::DeserializeOwned;
use serde_json::Value;

use crate::values::{catalogued_capabilities, fixtures, object_examples, tagged_examples};

mod catalog;
use catalog::payloads;

/// npm package name for this crate's Node artifact.
pub const PACKAGE_NAME: &str = "@ployz/sdk";

const TYPESCRIPT_PREAMBLE: &str = "\
export type JsonValue =\n  | null\n  | boolean\n  | number\n  | string\n  | JsonValue[]\n  | JsonObject;\n\n\
export type JsonObject = { readonly [key: string]: JsonValue | undefined };\n\n\
export type SerdeResult<T, E> =\n  | { Ok: T }\n  | { Err: E };\n\n";

/// Generated TypeScript declarations and JSON fixtures.
pub struct Artifacts {
    pub payloads_dts: String,
    pub fixtures_json: String,
}

/// Build the checked-in `@ployz/sdk` artifacts from Rust types.
#[must_use]
pub fn artifacts() -> Artifacts {
    check_typescript_matches_serde();
    Artifacts {
        payloads_dts: typescript(),
        fixtures_json: pretty_json(&Value::Object(fixtures().into_iter().collect())),
    }
}

/// Write generated files under the napi package root.
///
/// Façade declarations (`connect` / `listHeld` / `register` / `revokePairing` /
/// `about` / `preview` / `previewProjectRemoval` / `run` / `removeVolumes` /
/// `dataLossIfMachineRemoved` / `removeMachine` /
/// `dataLossIfProjectDestroyed` / `destroyProject` /
/// `dataLossIfClusterDestroyed` / `destroyCluster` / `close`) live in handwritten
/// `index.d.ts` and are not emitted here.
///
/// # Errors
///
/// Returns filesystem errors from creating `generated/` or writing files.
pub fn write_generated(root: &Path) -> std::io::Result<()> {
    let artifacts = artifacts();
    fs::create_dir_all(root.join("generated"))?;
    fs::write(root.join("generated/payloads.d.ts"), artifacts.payloads_dts)?;
    fs::write(
        root.join("generated/fixtures.json"),
        artifacts.fixtures_json,
    )?;
    Ok(())
}

/// Compare generated output to the files checked in under `root`.
#[must_use]
pub fn drift(root: &Path) -> Option<String> {
    let expected = artifacts();
    let mut problems = Vec::new();
    match fs::read_to_string(root.join("generated/payloads.d.ts")) {
        Ok(on_disk) if on_disk == expected.payloads_dts => {}
        Ok(_) => problems.push("generated/payloads.d.ts is stale".to_owned()),
        Err(error) => problems.push(format!("generated/payloads.d.ts: {error}")),
    }
    match fs::read_to_string(root.join("generated/fixtures.json")) {
        Ok(on_disk) if on_disk == expected.fixtures_json => {}
        Ok(_) => problems.push("generated/fixtures.json is stale".to_owned()),
        Err(error) => problems.push(format!("generated/fixtures.json: {error}")),
    }
    if problems.is_empty() {
        None
    } else {
        problems.push(
            "regenerate with `cargo run -p ployz-sdk-payloads --bin generate-sdk-types`".to_owned(),
        );
        Some(problems.join("\n"))
    }
}

fn typescript() -> String {
    let mut out = String::from(
        "// Generated by `cargo run -p ployz-sdk-payloads --bin generate-sdk-types`. Do not edit.\n\n",
    );
    out.push_str(TYPESCRIPT_PREAMBLE);
    for (_, declaration) in declarations() {
        out.push_str("export ");
        out.push_str(&declaration);
        out.push_str("\n\n");
    }
    out.push_str(&capability_typescript());
    out.push_str("export declare function packageName(): \"");
    out.push_str(PACKAGE_NAME);
    out.push_str("\";\n");
    out
}

macro_rules! declare {
    ($($payload:ty),* $(,)?) => {
        vec![$((
            stringify!($payload).rsplit("::").next().unwrap_or_default().trim().to_owned(),
            <$payload as ts_rs::TS>::decl(&config()),
        )),*]
    };
}

/// 64-bit integers cross the wire as JSON numbers, so they stay `number`.
/// `ts-rs` would otherwise emit `bigint`, which `JSON.parse` never produces.
fn config() -> ts_rs::Config {
    ts_rs::Config::new().with_large_int("number")
}

/// Every payload declaration, derived from the Rust type by `ts-rs`.
fn declarations() -> Vec<(String, String)> {
    payloads!(declare)
}

fn capability_typescript() -> String {
    let rows = catalogued_capabilities();
    let mut out = String::new();
    for (rust_name, wire) in &rows {
        out.push_str("export const ");
        out.push_str(rust_name);
        out.push_str(": CapabilityName = \"");
        out.push_str(wire);
        out.push_str("\";\n");
    }
    out.push('\n');
    out.push_str("export const CATALOGUED_CAPABILITIES = [\n");
    for (_, wire) in &rows {
        out.push_str("  \"");
        out.push_str(wire);
        out.push_str("\",\n");
    }
    out.push_str("] as const;\n\n");
    out.push_str(
        "export type CataloguedCapability = (typeof CATALOGUED_CAPABILITIES)[number];\n\n",
    );
    out
}

/// Field names in the derived TypeScript must match what serde actually writes.
///
/// `ts-rs` reads the Rust type, not serde's output, so it silently derives the
/// wrong shape for anything using `#[serde(into = "..Wire")]`, `#[serde(flatten)]`,
/// or a hand-written `Serialize`. The examples are produced by serde itself, so
/// they are the authority; a type that disagrees needs `#[ts(as = "..")]`.
fn check_typescript_matches_serde() {
    let declared: BTreeMap<String, String> = declarations().into_iter().collect();
    let mut problems = Vec::new();
    for (name, example) in object_examples() {
        if !declared.contains_key(name) {
            continue;
        }
        let Some(object) = example.as_object() else {
            continue;
        };
        let fields = declared_fields(name, &declared, &mut BTreeSet::new());
        for key in object.keys() {
            if !fields.contains(key.as_str()) {
                problems.push(format!("{name}: serde writes `{key}`, TypeScript does not"));
            }
        }
    }
    for (name, examples) in tagged_examples() {
        if !declared.contains_key(name) {
            continue;
        }
        for example in examples {
            let Some(object) = example.as_object() else {
                continue;
            };
            let fields = declared_fields(name, &declared, &mut BTreeSet::new());
            for key in object.keys() {
                if !fields.contains(key.as_str()) {
                    problems.push(format!("{name}: serde writes `{key}`, TypeScript does not"));
                }
            }
        }
    }
    assert!(problems.is_empty(), "{}", problems.join("\n"));
}

/// Field names in a declaration, following references into other declarations.
///
/// A variant that serde flattens appears as an intersection (`{ "state": "configured" }
/// & ConfiguredHealthcheck`), so the fields live in the referenced type.
fn declared_fields<'decl>(
    name: &str,
    declared: &'decl BTreeMap<String, String>,
    seen: &mut BTreeSet<String>,
) -> BTreeSet<&'decl str> {
    let mut fields = BTreeSet::new();
    if !seen.insert(name.to_owned()) {
        return fields;
    }
    let Some(declaration) = declared.get(name) else {
        return fields;
    };
    for (index, _) in declaration.match_indices(':') {
        let head = declaration[..index].trim_end();
        let head = head.strip_suffix('?').unwrap_or(head);
        // Keys may be quoted (`"state":`) or bare (`size_bytes:`).
        let head = head.trim_end_matches('"');
        let start = head
            .rfind(|c: char| !(c.is_alphanumeric() || c == '_'))
            .map_or(0, |i| i + 1);
        let field = &head[start..];
        if !field.is_empty() {
            fields.insert(field);
        }
    }
    // Only an intersection contributes fields at this level. `field: Other` nests,
    // so its fields are not this type's and must not be counted here.
    for arm in declaration.split('&').skip(1) {
        let referenced = arm
            .trim_start()
            .split(|c: char| !(c.is_alphanumeric() || c == '_'))
            .next()
            .unwrap_or_default();
        if referenced != name && declared.contains_key(referenced) {
            fields.extend(declared_fields(referenced, declared, seen));
        }
    }
    fields
}

fn pretty_json(value: &Value) -> String {
    let mut encoded = serde_json::to_string_pretty(value).expect("fixtures are valid JSON");
    encoded.push('\n');
    encoded
}

/// Package directory for the `@ployz/sdk` napi artifact.
#[must_use]
pub fn sdk_package_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("ployz-sdk")
}

/// Decode a fixture as `T`.
#[must_use]
pub fn decode_fixture<T: DeserializeOwned>(value: &Value) -> T {
    serde::Deserialize::deserialize(value).expect("fixture matches the Rust type")
}
