//! Deterministic TypeScript declarations for `@ployz/sdk` public payloads.
//!
//! The declarations describe exactly what the SDK's Rust layer emits and
//! accepts, not what a newer ployzd might send: Rust owns that version
//! boundary. So object types are exact (Rust drops unknown fields on
//! re-serialization) and tagged unions are closed (a `#[serde(tag)]` enum
//! fails to decode an unknown tag inside the SDK, so JavaScript never sees
//! one). The one state Rust passes through, `ContainerRuntimeObservation`'s
//! unknown case, is a named arm rather than a hole. Open strings stay open
//! because Rust passes those through as observed.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    path::{Path, PathBuf},
};

use serde::de::DeserializeOwned;
use serde_json::{Map, Value};

use crate::values::{catalogued_capabilities, object_examples, tagged_decoders, tagged_examples};

mod catalog;
use catalog::{PAYLOADS, Shape};

/// npm package name for this crate's Node artifact.
pub const PACKAGE_NAME: &str = "@ployz/sdk";

const TYPESCRIPT_PREAMBLE: &str = "\
export type JsonValue =\n  | null\n  | boolean\n  | number\n  | string\n  | JsonValue[]\n  | JsonObject;\n\n\
export type JsonObject = { readonly [key: string]: JsonValue | undefined };\n\n";

fn generated_types() -> String {
    check_object_fields_match_rust();
    check_internally_tagged_variants_match_rust();
    check_tagged_payloads_reject_unknown_tags();
    check_closed_strings_match_rust();
    check_json_value_fields_are_intentional();
    typescript()
}

/// Write generated files under the napi package root.
///
/// Façade declarations (`connect` / `listHeld` / `register` / `revokePairing` /
/// `about` / `preview` / `previewProjectRemoval` / `run` / `removeVolumes` /
/// `dataLossIfMachineRemoved` / `removeMachine` /
/// `dataLossIfProjectDestroyed` / `destroyProject` /
/// `dataLossIfClusterDestroyed` / `destroyCluster` / `close`) live in handwritten
/// `index.d.ts` and are not emitted here.
///
/// # Errors
///
/// Returns filesystem errors from creating `generated/` or writing files.
pub fn write_generated(root: &Path) -> std::io::Result<()> {
    fs::create_dir_all(root.join("generated"))?;
    fs::write(root.join("generated/payloads.d.ts"), generated_types())?;
    Ok(())
}

/// Compare generated output to the files checked in under `root`.
#[must_use]
pub fn drift(root: &Path) -> Option<String> {
    let expected = generated_types();
    let mut problems = Vec::new();
    match fs::read_to_string(root.join("generated/payloads.d.ts")) {
        Ok(on_disk) if on_disk == expected => {}
        Ok(_) => problems.push("generated/payloads.d.ts is stale".to_owned()),
        Err(error) => problems.push(format!("generated/payloads.d.ts: {error}")),
    }
    if problems.is_empty() {
        None
    } else {
        problems.push(
            "regenerate with `cargo run -p ployz-sdk-payloads --bin generate-sdk-types`".to_owned(),
        );
        Some(problems.join("\n"))
    }
}

fn typescript() -> String {
    let mut out = String::from(
        "// Generated by `cargo run -p ployz-sdk-payloads --bin generate-sdk-types`. Do not edit.\n\n",
    );
    out.push_str(TYPESCRIPT_PREAMBLE);
    for (name, shape) in PAYLOADS {
        out.push_str(&emit_shape(name, shape));
        out.push('\n');
    }
    out.push_str(&capability_typescript());
    out.push_str("export declare function packageName(): \"");
    out.push_str(PACKAGE_NAME);
    out.push_str("\";\n");
    out
}

fn emit_shape(name: &str, shape: &Shape) -> String {
    match shape {
        Shape::Alias(ts) => format!("export type {name} = {ts};\n"),
        Shape::Branded => {
            format!("export type {name} = string & {{ readonly __brand: \"{name}\" }};\n")
        }
        Shape::OpenString(known) => {
            format!(
                "export type {name} = {} | (string & {{}});\n",
                quoted_union(known)
            )
        }
        Shape::ClosedString(known) => {
            format!("export type {name} = {};\n", quoted_union(known))
        }
        Shape::Object { params, fields } => emit_object(name, params, fields),
        Shape::InternallyTagged {
            tag,
            params,
            variants,
        } => emit_internally_tagged(name, params, tag, variants),
    }
}

fn quoted_union(known: &[&str]) -> String {
    known
        .iter()
        .map(|value| format!("\"{value}\""))
        .collect::<Vec<_>>()
        .join(" | ")
}

fn emit_object(name: &str, params: &str, fields: &[(&str, &str)]) -> String {
    let mut body = format!("export type {name}{params} = {{\n");
    for (field, ts) in fields {
        let (ts, optional) = strip_optional(ts);
        body.push_str("  ");
        body.push_str(field);
        if optional {
            body.push('?');
        }
        body.push_str(": ");
        body.push_str(ts);
        body.push_str(";\n");
    }
    body.push_str("};\n");
    body
}

fn emit_internally_tagged(
    name: &str,
    params: &str,
    tag: &str,
    variants: &[(&str, &[(&str, &str)])],
) -> String {
    // No trailing `{ tag?: string }` arm: Rust rejects an unknown tag before
    // JavaScript could see one, and the arm defeats discriminant narrowing.
    let mut arms = Vec::new();
    for (tag_value, fields) in variants {
        let mut members = vec![format!("{tag}: \"{tag_value}\"")];
        for (field, ts) in *fields {
            let (ts, optional) = strip_optional(ts);
            if optional {
                members.push(format!("{field}?: {ts}"));
            } else {
                members.push(format!("{field}: {ts}"));
            }
        }
        arms.push(format!("{{ {} }}", members.join("; ")));
    }
    format!(
        "export type {name}{params} =\n  | {};\n",
        arms.join("\n  | ")
    )
}

fn capability_typescript() -> String {
    let rows = catalogued_capabilities();
    let mut out = String::new();
    for (rust_name, wire) in &rows {
        out.push_str("export const ");
        out.push_str(rust_name);
        out.push_str(": CapabilityName = \"");
        out.push_str(wire);
        out.push_str("\";\n");
    }
    out.push('\n');
    out.push_str("export const CATALOGUED_CAPABILITIES = [\n");
    for (_, wire) in &rows {
        out.push_str("  \"");
        out.push_str(wire);
        out.push_str("\",\n");
    }
    out.push_str("] as const;\n\n");
    out.push_str(
        "export type CataloguedCapability = (typeof CATALOGUED_CAPABILITIES)[number];\n\n",
    );
    out
}

fn check_object_fields_match_rust() {
    let examples = object_examples();
    for (name, shape) in PAYLOADS {
        let Shape::Object { fields, .. } = shape else {
            continue;
        };
        let value = examples
            .get(*name)
            .unwrap_or_else(|| panic!("{name} Object shape has no serde example"));
        let object = value
            .as_object()
            .unwrap_or_else(|| panic!("{name} serde value is not an object"));
        for key in object.keys() {
            assert!(
                fields.iter().any(|(field, _)| field == key),
                "{name} TypeScript fields missing serde key {key}"
            );
        }
        for (field, ts) in *fields {
            if strip_optional(ts).1 {
                continue;
            }
            assert!(
                object.contains_key(*field),
                "{name} serde value missing field {field}"
            );
        }
    }
}

fn check_internally_tagged_variants_match_rust() {
    let examples = tagged_examples();
    for (name, shape) in PAYLOADS {
        let Shape::InternallyTagged { tag, variants, .. } = shape else {
            continue;
        };
        let mut seen = BTreeSet::new();
        for value in serde_examples(name, &examples) {
            let object = value
                .as_object()
                .unwrap_or_else(|| panic!("{name} serde example is not an object"));
            let wire = object
                .get(*tag)
                .and_then(Value::as_str)
                .unwrap_or_else(|| panic!("{name} serde example is missing tag {tag}"));
            let Some((_, fields)) = variants.iter().find(|(variant, _)| *variant == wire) else {
                panic!("{name} TypeScript is missing variant {wire}; generated unions are closed");
            };
            for key in object.keys().filter(|key| key != tag) {
                assert!(
                    fields.iter().any(|(field, _)| field == key),
                    "{name}.{wire} TypeScript fields missing serde key {key}"
                );
            }
            for (field, ts) in *fields {
                assert!(
                    strip_optional(ts).1 || object.contains_key(*field),
                    "{name}.{wire} serde value missing field {field}"
                );
            }
            seen.insert(wire.to_owned());
        }
        for (variant, _) in *variants {
            assert!(
                seen.contains(*variant),
                "{name} TypeScript variant {variant} has no serde example"
            );
        }
    }
}

/// The one tagged payload whose Rust type keeps an unknown tag as observed.
const PASSTHROUGH_PAYLOAD: &str = "ContainerRuntimeObservation";

fn check_tagged_payloads_reject_unknown_tags() {
    let decoders = tagged_decoders();
    let examples = tagged_examples();
    for name in decoders.keys() {
        assert!(
            PAYLOADS.iter().any(|(payload, shape)| payload == name
                && matches!(shape, Shape::InternallyTagged { .. })),
            "{name} has a decoder but is not a tagged payload in the catalog"
        );
    }
    for (name, shape) in PAYLOADS {
        let Shape::InternallyTagged { tag, .. } = shape else {
            continue;
        };
        let decodes = decoders
            .get(name)
            .unwrap_or_else(|| panic!("{name} has no decoder"));
        for example in serde_examples(name, &examples) {
            assert!(
                decodes(example.clone()),
                "{name} decoder rejects its own serde example; the table row names the wrong type"
            );
        }
        let unknown = Value::Object(Map::from_iter([(
            (*tag).to_owned(),
            Value::from("from_a_newer_daemon"),
        )]));
        if *name == PASSTHROUGH_PAYLOAD {
            assert!(
                decodes(unknown),
                "{name} must keep an unknown {tag} as observed; its union names that case"
            );
        } else {
            assert!(
                !decodes(unknown),
                "{name} accepts an unknown {tag}, so its closed TypeScript union would be false"
            );
        }
    }
}

fn check_json_value_fields_are_intentional() {
    for (name, shape) in PAYLOADS {
        match shape {
            Shape::Alias(ts) => assert_json_field_is_intentional(name, "alias", ts),
            Shape::Branded | Shape::OpenString(_) | Shape::ClosedString(_) => {}
            Shape::Object { fields, .. } => {
                for (field, ts) in *fields {
                    assert_json_field_is_intentional(name, field, ts);
                }
            }
            Shape::InternallyTagged { variants, .. } => {
                for (variant, fields) in *variants {
                    for (field, ts) in *fields {
                        assert_json_field_is_intentional(name, &format!("{variant}.{field}"), ts);
                    }
                }
            }
        }
    }
}

fn assert_json_field_is_intentional(type_name: &str, field: &str, ts: &str) {
    let inner = strip_optional(ts).0;
    if inner.contains("JsonValue") || inner.contains("JsonObject") {
        assert!(
            matches!(
                (type_name, field),
                ("RpcError", "details") | (PASSTHROUGH_PAYLOAD, "unrecognized.raw")
            ),
            "{type_name}.{field} uses {ts}; only RpcError.details and {PASSTHROUGH_PAYLOAD}.unrecognized.raw may stay JsonValue"
        );
    }
}

fn check_closed_strings_match_rust() {
    let examples = tagged_examples();
    for (name, shape) in PAYLOADS {
        let Shape::ClosedString(known) = shape else {
            continue;
        };
        let mut seen = BTreeSet::new();
        for value in serde_examples(name, &examples) {
            let wire = value
                .as_str()
                .unwrap_or_else(|| panic!("{name} serde example is not a string"));
            assert!(
                known.contains(&wire),
                "{name} TypeScript is missing closed wire {wire}"
            );
            seen.insert(wire.to_owned());
        }
        for wire in *known {
            assert!(
                seen.contains(*wire),
                "{name} TypeScript wire {wire} has no serde example"
            );
        }
    }
}

fn serde_examples<'a>(name: &str, examples: &'a BTreeMap<&'static str, Vec<Value>>) -> &'a [Value] {
    let values = examples
        .get(name)
        .unwrap_or_else(|| panic!("{name} shape has no serde example"));
    assert!(!values.is_empty(), "{name} shape has no serde example");
    values
}

fn strip_optional(ts: &str) -> (&str, bool) {
    ts.strip_suffix('?')
        .map_or((ts, false), |inner| (inner, true))
}

/// Package directory for the `@ployz/sdk` napi artifact.
#[must_use]
pub fn sdk_package_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("ployz-sdk")
}

/// Decode a fixture as `T`.
#[must_use]
pub fn decode_fixture<T: DeserializeOwned>(value: &Value) -> T {
    serde::Deserialize::deserialize(value).expect("fixture matches the Rust type")
}
