/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as ProtectedCloudRouteRouteImport } from './routes/_protected/cloud/route'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicAuthRouteImport } from './routes/_public/auth'
import { Route as PublicDocsRouteImport } from './routes/_public/docs'
import { Route as PublicHomeRouteImport } from './routes/_public/home'
import { Route as PublicPricingRouteImport } from './routes/_public/pricing'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'
import { Route as ApiWaitlistRouteImport } from './routes/api/waitlist'
import { Route as ProtectedCloudIndexRouteImport } from './routes/_protected/cloud/index'
import { Route as ProtectedCloudOrganizationSlugRouteRouteImport } from './routes/_protected/cloud/$organizationSlug/route'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAuthGithubRouteImport } from './routes/api/auth/github'
import { Route as ApiEnrollTokenRouteImport } from './routes/api/enroll/$token'
import { Route as ApiGithubWebhookRouteImport } from './routes/api/github/webhook'
import { Route as ApiRuntimeEventsRouteImport } from './routes/api/runtime/events'
import { Route as ApiShapesTableRouteImport } from './routes/api/shapes/$table'
import { Route as ProtectedCloudOrganizationSlugOrgRouteRouteImport } from './routes/_protected/cloud/$organizationSlug/_org/route'
import { Route as ProtectedCloudOrganizationSlugProjectRouteRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/route'
import { Route as ApiEnrollTokenCallbackRouteImport } from './routes/api/enroll/$token/callback'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/route'
import { Route as ProtectedCloudOrganizationSlugProjectNewRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/new'
import { Route as ProtectedCloudOrganizationSlugOrgChar126IndexRouteImport } from './routes/_protected/cloud/$organizationSlug/_org/~/index'
import { Route as ProtectedCloudOrganizationSlugOrgChar126BillingRouteImport } from './routes/_protected/cloud/$organizationSlug/_org/~/billing'
import { Route as ProtectedCloudOrganizationSlugOrgChar126DeploymentsRouteImport } from './routes/_protected/cloud/$organizationSlug/_org/~/deployments'
import { Route as ProtectedCloudOrganizationSlugOrgChar126LogsRouteImport } from './routes/_protected/cloud/$organizationSlug/_org/~/logs'
import { Route as ProtectedCloudOrganizationSlugOrgChar126SettingsRouteImport } from './routes/_protected/cloud/$organizationSlug/_org/~/settings'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugIndexRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/index'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/route'
import { Route as ProtectedCloudOrganizationSlugOrgChar126ServersIndexRouteImport } from './routes/_protected/cloud/$organizationSlug/_org/~/servers/index'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/route'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/deployments'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/logs'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/settings'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/index'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/resources/$resourceId'
import { Route as ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRouteImport } from './routes/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/services/$serviceId'

const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCloudRouteRoute = ProtectedCloudRouteRouteImport.update({
  id: '/cloud',
  path: '/cloud',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicAuthRoute = PublicAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicDocsRoute = PublicDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicHomeRoute = PublicHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicPricingRoute = PublicPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => PublicRouteRoute,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWaitlistRoute = ApiWaitlistRouteImport.update({
  id: '/api/waitlist',
  path: '/api/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCloudIndexRoute = ProtectedCloudIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedCloudRouteRoute,
} as any)
const ProtectedCloudOrganizationSlugRouteRoute =
  ProtectedCloudOrganizationSlugRouteRouteImport.update({
    id: '/$organizationSlug',
    path: '/$organizationSlug',
    getParentRoute: () => ProtectedCloudRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthGithubRoute = ApiAuthGithubRouteImport.update({
  id: '/api/auth/github',
  path: '/api/auth/github',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnrollTokenRoute = ApiEnrollTokenRouteImport.update({
  id: '/api/enroll/$token',
  path: '/api/enroll/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGithubWebhookRoute = ApiGithubWebhookRouteImport.update({
  id: '/api/github/webhook',
  path: '/api/github/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRuntimeEventsRoute = ApiRuntimeEventsRouteImport.update({
  id: '/api/runtime/events',
  path: '/api/runtime/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiShapesTableRoute = ApiShapesTableRouteImport.update({
  id: '/api/shapes/$table',
  path: '/api/shapes/$table',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedCloudOrganizationSlugOrgRouteRoute =
  ProtectedCloudOrganizationSlugOrgRouteRouteImport.update({
    id: '/_org',
    getParentRoute: () => ProtectedCloudOrganizationSlugRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugProjectRouteRoute =
  ProtectedCloudOrganizationSlugProjectRouteRouteImport.update({
    id: '/_project',
    getParentRoute: () => ProtectedCloudOrganizationSlugRouteRoute,
  } as any)
const ApiEnrollTokenCallbackRoute = ApiEnrollTokenCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => ApiEnrollTokenRoute,
} as any)
const ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteImport.update({
    id: '/$projectSlug',
    path: '/$projectSlug',
    getParentRoute: () => ProtectedCloudOrganizationSlugProjectRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugProjectNewRoute =
  ProtectedCloudOrganizationSlugProjectNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ProtectedCloudOrganizationSlugProjectRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugOrgChar126IndexRoute =
  ProtectedCloudOrganizationSlugOrgChar126IndexRouteImport.update({
    id: '/~/',
    path: '/~/',
    getParentRoute: () => ProtectedCloudOrganizationSlugOrgRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugOrgChar126BillingRoute =
  ProtectedCloudOrganizationSlugOrgChar126BillingRouteImport.update({
    id: '/~/billing',
    path: '/~/billing',
    getParentRoute: () => ProtectedCloudOrganizationSlugOrgRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute =
  ProtectedCloudOrganizationSlugOrgChar126DeploymentsRouteImport.update({
    id: '/~/deployments',
    path: '/~/deployments',
    getParentRoute: () => ProtectedCloudOrganizationSlugOrgRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugOrgChar126LogsRoute =
  ProtectedCloudOrganizationSlugOrgChar126LogsRouteImport.update({
    id: '/~/logs',
    path: '/~/logs',
    getParentRoute: () => ProtectedCloudOrganizationSlugOrgRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugOrgChar126SettingsRoute =
  ProtectedCloudOrganizationSlugOrgChar126SettingsRouteImport.update({
    id: '/~/settings',
    path: '/~/settings',
    getParentRoute: () => ProtectedCloudOrganizationSlugOrgRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () =>
      ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteImport.update(
    {
      id: '/$environmentSlug',
      path: '/$environmentSlug',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute,
    } as any,
  )
const ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute =
  ProtectedCloudOrganizationSlugOrgChar126ServersIndexRouteImport.update({
    id: '/~/servers/',
    path: '/~/servers/',
    getParentRoute: () => ProtectedCloudOrganizationSlugOrgRouteRoute,
  } as any)
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteImport.update(
    {
      id: '/_canvas',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute,
    } as any,
  )
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRouteImport.update(
    {
      id: '/deployments',
      path: '/deployments',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute,
    } as any,
  )
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRouteImport.update(
    {
      id: '/logs',
      path: '/logs',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute,
    } as any,
  )
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRouteImport.update(
    {
      id: '/settings',
      path: '/settings',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute,
    } as any,
  )
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute,
    } as any,
  )
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRouteImport.update(
    {
      id: '/resources/$resourceId',
      path: '/resources/$resourceId',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute,
    } as any,
  )
const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRouteImport.update(
    {
      id: '/services/$serviceId',
      path: '/services/$serviceId',
      getParentRoute: () =>
        ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/cloud': typeof ProtectedCloudRouteRouteWithChildren
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth': typeof PublicAuthRoute
  '/docs': typeof PublicDocsRoute
  '/home': typeof PublicHomeRoute
  '/pricing': typeof PublicPricingRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/cloud/$organizationSlug': typeof ProtectedCloudOrganizationSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/enroll/$token': typeof ApiEnrollTokenRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/runtime/events': typeof ApiRuntimeEventsRoute
  '/api/shapes/$table': typeof ApiShapesTableRoute
  '/cloud/': typeof ProtectedCloudIndexRoute
  '/api/enroll/$token/callback': typeof ApiEnrollTokenCallbackRoute
  '/cloud/$organizationSlug/$projectSlug': typeof ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteWithChildren
  '/cloud/$organizationSlug/new': typeof ProtectedCloudOrganizationSlugProjectNewRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteWithChildren
  '/cloud/$organizationSlug/~/billing': typeof ProtectedCloudOrganizationSlugOrgChar126BillingRoute
  '/cloud/$organizationSlug/~/deployments': typeof ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute
  '/cloud/$organizationSlug/~/logs': typeof ProtectedCloudOrganizationSlugOrgChar126LogsRoute
  '/cloud/$organizationSlug/~/settings': typeof ProtectedCloudOrganizationSlugOrgChar126SettingsRoute
  '/cloud/$organizationSlug/~/': typeof ProtectedCloudOrganizationSlugOrgChar126IndexRoute
  '/cloud/$organizationSlug/$projectSlug/': typeof ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/deployments': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/logs': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/settings': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute
  '/cloud/$organizationSlug/~/servers/': typeof ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/resources/$resourceId': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/services/$serviceId': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/auth': typeof PublicAuthRoute
  '/docs': typeof PublicDocsRoute
  '/home': typeof PublicHomeRoute
  '/pricing': typeof PublicPricingRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/cloud/$organizationSlug': typeof ProtectedCloudOrganizationSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/enroll/$token': typeof ApiEnrollTokenRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/runtime/events': typeof ApiRuntimeEventsRoute
  '/api/shapes/$table': typeof ApiShapesTableRoute
  '/cloud': typeof ProtectedCloudIndexRoute
  '/api/enroll/$token/callback': typeof ApiEnrollTokenCallbackRoute
  '/cloud/$organizationSlug/new': typeof ProtectedCloudOrganizationSlugProjectNewRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute
  '/cloud/$organizationSlug/~/billing': typeof ProtectedCloudOrganizationSlugOrgChar126BillingRoute
  '/cloud/$organizationSlug/~/deployments': typeof ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute
  '/cloud/$organizationSlug/~/logs': typeof ProtectedCloudOrganizationSlugOrgChar126LogsRoute
  '/cloud/$organizationSlug/~/settings': typeof ProtectedCloudOrganizationSlugOrgChar126SettingsRoute
  '/cloud/$organizationSlug/~': typeof ProtectedCloudOrganizationSlugOrgChar126IndexRoute
  '/cloud/$organizationSlug/$projectSlug': typeof ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/deployments': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/logs': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/settings': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute
  '/cloud/$organizationSlug/~/servers': typeof ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/resources/$resourceId': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute
  '/cloud/$organizationSlug/$projectSlug/$environmentSlug/services/$serviceId': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_protected/cloud': typeof ProtectedCloudRouteRouteWithChildren
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_public/auth': typeof PublicAuthRoute
  '/_public/docs': typeof PublicDocsRoute
  '/_public/home': typeof PublicHomeRoute
  '/_public/pricing': typeof PublicPricingRoute
  '/api/inngest': typeof ApiInngestRoute
  '/api/waitlist': typeof ApiWaitlistRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/cloud/$organizationSlug': typeof ProtectedCloudOrganizationSlugRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/auth/github': typeof ApiAuthGithubRoute
  '/api/enroll/$token': typeof ApiEnrollTokenRouteWithChildren
  '/api/github/webhook': typeof ApiGithubWebhookRoute
  '/api/runtime/events': typeof ApiRuntimeEventsRoute
  '/api/shapes/$table': typeof ApiShapesTableRoute
  '/_protected/cloud/': typeof ProtectedCloudIndexRoute
  '/_protected/cloud/$organizationSlug/_org': typeof ProtectedCloudOrganizationSlugOrgRouteRouteWithChildren
  '/_protected/cloud/$organizationSlug/_project': typeof ProtectedCloudOrganizationSlugProjectRouteRouteWithChildren
  '/api/enroll/$token/callback': typeof ApiEnrollTokenCallbackRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug': typeof ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteWithChildren
  '/_protected/cloud/$organizationSlug/_project/new': typeof ProtectedCloudOrganizationSlugProjectNewRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteWithChildren
  '/_protected/cloud/$organizationSlug/_org/~/billing': typeof ProtectedCloudOrganizationSlugOrgChar126BillingRoute
  '/_protected/cloud/$organizationSlug/_org/~/deployments': typeof ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute
  '/_protected/cloud/$organizationSlug/_org/~/logs': typeof ProtectedCloudOrganizationSlugOrgChar126LogsRoute
  '/_protected/cloud/$organizationSlug/_org/~/settings': typeof ProtectedCloudOrganizationSlugOrgChar126SettingsRoute
  '/_protected/cloud/$organizationSlug/_org/~/': typeof ProtectedCloudOrganizationSlugOrgChar126IndexRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/': typeof ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteWithChildren
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/deployments': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/logs': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/settings': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute
  '/_protected/cloud/$organizationSlug/_org/~/servers/': typeof ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/resources/$resourceId': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute
  '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/services/$serviceId': typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cloud'
    | '/dashboard'
    | '/auth'
    | '/docs'
    | '/home'
    | '/pricing'
    | '/api/inngest'
    | '/api/waitlist'
    | '/cloud/$organizationSlug'
    | '/api/auth/$'
    | '/api/auth/github'
    | '/api/enroll/$token'
    | '/api/github/webhook'
    | '/api/runtime/events'
    | '/api/shapes/$table'
    | '/cloud/'
    | '/api/enroll/$token/callback'
    | '/cloud/$organizationSlug/$projectSlug'
    | '/cloud/$organizationSlug/new'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug'
    | '/cloud/$organizationSlug/~/billing'
    | '/cloud/$organizationSlug/~/deployments'
    | '/cloud/$organizationSlug/~/logs'
    | '/cloud/$organizationSlug/~/settings'
    | '/cloud/$organizationSlug/~/'
    | '/cloud/$organizationSlug/$projectSlug/'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/deployments'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/logs'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/settings'
    | '/cloud/$organizationSlug/~/servers/'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/resources/$resourceId'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/services/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth'
    | '/docs'
    | '/home'
    | '/pricing'
    | '/api/inngest'
    | '/api/waitlist'
    | '/cloud/$organizationSlug'
    | '/api/auth/$'
    | '/api/auth/github'
    | '/api/enroll/$token'
    | '/api/github/webhook'
    | '/api/runtime/events'
    | '/api/shapes/$table'
    | '/cloud'
    | '/api/enroll/$token/callback'
    | '/cloud/$organizationSlug/new'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug'
    | '/cloud/$organizationSlug/~/billing'
    | '/cloud/$organizationSlug/~/deployments'
    | '/cloud/$organizationSlug/~/logs'
    | '/cloud/$organizationSlug/~/settings'
    | '/cloud/$organizationSlug/~'
    | '/cloud/$organizationSlug/$projectSlug'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/deployments'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/logs'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/settings'
    | '/cloud/$organizationSlug/~/servers'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/resources/$resourceId'
    | '/cloud/$organizationSlug/$projectSlug/$environmentSlug/services/$serviceId'
  id:
    | '__root__'
    | '/_protected'
    | '/_public'
    | '/_protected/cloud'
    | '/_protected/dashboard'
    | '/_public/auth'
    | '/_public/docs'
    | '/_public/home'
    | '/_public/pricing'
    | '/api/inngest'
    | '/api/waitlist'
    | '/_public/'
    | '/_protected/cloud/$organizationSlug'
    | '/api/auth/$'
    | '/api/auth/github'
    | '/api/enroll/$token'
    | '/api/github/webhook'
    | '/api/runtime/events'
    | '/api/shapes/$table'
    | '/_protected/cloud/'
    | '/_protected/cloud/$organizationSlug/_org'
    | '/_protected/cloud/$organizationSlug/_project'
    | '/api/enroll/$token/callback'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug'
    | '/_protected/cloud/$organizationSlug/_project/new'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug'
    | '/_protected/cloud/$organizationSlug/_org/~/billing'
    | '/_protected/cloud/$organizationSlug/_org/~/deployments'
    | '/_protected/cloud/$organizationSlug/_org/~/logs'
    | '/_protected/cloud/$organizationSlug/_org/~/settings'
    | '/_protected/cloud/$organizationSlug/_org/~/'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/deployments'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/logs'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/settings'
    | '/_protected/cloud/$organizationSlug/_org/~/servers/'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/resources/$resourceId'
    | '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/services/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  ApiInngestRoute: typeof ApiInngestRoute
  ApiWaitlistRoute: typeof ApiWaitlistRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiAuthGithubRoute: typeof ApiAuthGithubRoute
  ApiEnrollTokenRoute: typeof ApiEnrollTokenRouteWithChildren
  ApiGithubWebhookRoute: typeof ApiGithubWebhookRoute
  ApiRuntimeEventsRoute: typeof ApiRuntimeEventsRoute
  ApiShapesTableRoute: typeof ApiShapesTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/cloud': {
      id: '/_protected/cloud'
      path: '/cloud'
      fullPath: '/cloud'
      preLoaderRoute: typeof ProtectedCloudRouteRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/auth': {
      id: '/_public/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof PublicAuthRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/docs': {
      id: '/_public/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof PublicDocsRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/home': {
      id: '/_public/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PublicHomeRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/pricing': {
      id: '/_public/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PublicPricingRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/waitlist': {
      id: '/api/waitlist'
      path: '/api/waitlist'
      fullPath: '/api/waitlist'
      preLoaderRoute: typeof ApiWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/cloud/': {
      id: '/_protected/cloud/'
      path: '/'
      fullPath: '/cloud/'
      preLoaderRoute: typeof ProtectedCloudIndexRouteImport
      parentRoute: typeof ProtectedCloudRouteRoute
    }
    '/_protected/cloud/$organizationSlug': {
      id: '/_protected/cloud/$organizationSlug'
      path: '/$organizationSlug'
      fullPath: '/cloud/$organizationSlug'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugRouteRouteImport
      parentRoute: typeof ProtectedCloudRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/github': {
      id: '/api/auth/github'
      path: '/api/auth/github'
      fullPath: '/api/auth/github'
      preLoaderRoute: typeof ApiAuthGithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enroll/$token': {
      id: '/api/enroll/$token'
      path: '/api/enroll/$token'
      fullPath: '/api/enroll/$token'
      preLoaderRoute: typeof ApiEnrollTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/github/webhook': {
      id: '/api/github/webhook'
      path: '/api/github/webhook'
      fullPath: '/api/github/webhook'
      preLoaderRoute: typeof ApiGithubWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/runtime/events': {
      id: '/api/runtime/events'
      path: '/api/runtime/events'
      fullPath: '/api/runtime/events'
      preLoaderRoute: typeof ApiRuntimeEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/shapes/$table': {
      id: '/api/shapes/$table'
      path: '/api/shapes/$table'
      fullPath: '/api/shapes/$table'
      preLoaderRoute: typeof ApiShapesTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/cloud/$organizationSlug/_org': {
      id: '/_protected/cloud/$organizationSlug/_org'
      path: ''
      fullPath: '/cloud/$organizationSlug'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project': {
      id: '/_protected/cloud/$organizationSlug/_project'
      path: ''
      fullPath: '/cloud/$organizationSlug'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectRouteRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugRouteRoute
    }
    '/api/enroll/$token/callback': {
      id: '/api/enroll/$token/callback'
      path: '/callback'
      fullPath: '/api/enroll/$token/callback'
      preLoaderRoute: typeof ApiEnrollTokenCallbackRouteImport
      parentRoute: typeof ApiEnrollTokenRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/cloud/$organizationSlug/$projectSlug'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/new': {
      id: '/_protected/cloud/$organizationSlug/_project/new'
      path: '/new'
      fullPath: '/cloud/$organizationSlug/new'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectNewRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_org/~/': {
      id: '/_protected/cloud/$organizationSlug/_org/~/'
      path: '/~'
      fullPath: '/cloud/$organizationSlug/~/'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugOrgChar126IndexRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_org/~/billing': {
      id: '/_protected/cloud/$organizationSlug/_org/~/billing'
      path: '/~/billing'
      fullPath: '/cloud/$organizationSlug/~/billing'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugOrgChar126BillingRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_org/~/deployments': {
      id: '/_protected/cloud/$organizationSlug/_org/~/deployments'
      path: '/~/deployments'
      fullPath: '/cloud/$organizationSlug/~/deployments'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugOrgChar126DeploymentsRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_org/~/logs': {
      id: '/_protected/cloud/$organizationSlug/_org/~/logs'
      path: '/~/logs'
      fullPath: '/cloud/$organizationSlug/~/logs'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugOrgChar126LogsRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_org/~/settings': {
      id: '/_protected/cloud/$organizationSlug/_org/~/settings'
      path: '/~/settings'
      fullPath: '/cloud/$organizationSlug/~/settings'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugOrgChar126SettingsRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/'
      path: '/'
      fullPath: '/cloud/$organizationSlug/$projectSlug/'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugIndexRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug'
      path: '/$environmentSlug'
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_org/~/servers/': {
      id: '/_protected/cloud/$organizationSlug/_org/~/servers/'
      path: '/~/servers'
      fullPath: '/cloud/$organizationSlug/~/servers/'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugOrgChar126ServersIndexRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas'
      path: ''
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/deployments': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/deployments'
      path: '/deployments'
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug/deployments'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/logs': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/logs'
      path: '/logs'
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug/logs'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/settings': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/settings'
      path: '/settings'
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug/settings'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/'
      path: '/'
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug/'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/resources/$resourceId': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/resources/$resourceId'
      path: '/resources/$resourceId'
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug/resources/$resourceId'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute
    }
    '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/services/$serviceId': {
      id: '/_protected/cloud/$organizationSlug/_project/$projectSlug/$environmentSlug/_canvas/services/$serviceId'
      path: '/services/$serviceId'
      fullPath: '/cloud/$organizationSlug/$projectSlug/$environmentSlug/services/$serviceId'
      preLoaderRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRouteImport
      parentRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute
    }
  }
}

interface ProtectedCloudOrganizationSlugOrgRouteRouteChildren {
  ProtectedCloudOrganizationSlugOrgChar126BillingRoute: typeof ProtectedCloudOrganizationSlugOrgChar126BillingRoute
  ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute: typeof ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute
  ProtectedCloudOrganizationSlugOrgChar126LogsRoute: typeof ProtectedCloudOrganizationSlugOrgChar126LogsRoute
  ProtectedCloudOrganizationSlugOrgChar126SettingsRoute: typeof ProtectedCloudOrganizationSlugOrgChar126SettingsRoute
  ProtectedCloudOrganizationSlugOrgChar126IndexRoute: typeof ProtectedCloudOrganizationSlugOrgChar126IndexRoute
  ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute: typeof ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute
}

const ProtectedCloudOrganizationSlugOrgRouteRouteChildren: ProtectedCloudOrganizationSlugOrgRouteRouteChildren =
  {
    ProtectedCloudOrganizationSlugOrgChar126BillingRoute:
      ProtectedCloudOrganizationSlugOrgChar126BillingRoute,
    ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute:
      ProtectedCloudOrganizationSlugOrgChar126DeploymentsRoute,
    ProtectedCloudOrganizationSlugOrgChar126LogsRoute:
      ProtectedCloudOrganizationSlugOrgChar126LogsRoute,
    ProtectedCloudOrganizationSlugOrgChar126SettingsRoute:
      ProtectedCloudOrganizationSlugOrgChar126SettingsRoute,
    ProtectedCloudOrganizationSlugOrgChar126IndexRoute:
      ProtectedCloudOrganizationSlugOrgChar126IndexRoute,
    ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute:
      ProtectedCloudOrganizationSlugOrgChar126ServersIndexRoute,
  }

const ProtectedCloudOrganizationSlugOrgRouteRouteWithChildren =
  ProtectedCloudOrganizationSlugOrgRouteRoute._addFileChildren(
    ProtectedCloudOrganizationSlugOrgRouteRouteChildren,
  )

interface ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteChildren {
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute
}

const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteChildren: ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteChildren =
  {
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasIndexRoute,
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasResourcesResourceIdRoute,
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasServicesServiceIdRoute,
  }

const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteWithChildren =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute._addFileChildren(
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteChildren,
  )

interface ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteChildren {
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteWithChildren
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute
}

const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteChildren: ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteChildren =
  {
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugCanvasRouteRouteWithChildren,
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugDeploymentsRoute,
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugLogsRoute,
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugSettingsRoute,
  }

const ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteWithChildren =
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute._addFileChildren(
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteChildren,
  )

interface ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteChildren {
  ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteWithChildren
  ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute
}

const ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteChildren: ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteChildren =
  {
    ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugEnvironmentSlugRouteRouteWithChildren,
    ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugIndexRoute,
  }

const ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteWithChildren =
  ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute._addFileChildren(
    ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteChildren,
  )

interface ProtectedCloudOrganizationSlugProjectRouteRouteChildren {
  ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute: typeof ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteWithChildren
  ProtectedCloudOrganizationSlugProjectNewRoute: typeof ProtectedCloudOrganizationSlugProjectNewRoute
}

const ProtectedCloudOrganizationSlugProjectRouteRouteChildren: ProtectedCloudOrganizationSlugProjectRouteRouteChildren =
  {
    ProtectedCloudOrganizationSlugProjectProjectSlugRouteRoute:
      ProtectedCloudOrganizationSlugProjectProjectSlugRouteRouteWithChildren,
    ProtectedCloudOrganizationSlugProjectNewRoute:
      ProtectedCloudOrganizationSlugProjectNewRoute,
  }

const ProtectedCloudOrganizationSlugProjectRouteRouteWithChildren =
  ProtectedCloudOrganizationSlugProjectRouteRoute._addFileChildren(
    ProtectedCloudOrganizationSlugProjectRouteRouteChildren,
  )

interface ProtectedCloudOrganizationSlugRouteRouteChildren {
  ProtectedCloudOrganizationSlugOrgRouteRoute: typeof ProtectedCloudOrganizationSlugOrgRouteRouteWithChildren
  ProtectedCloudOrganizationSlugProjectRouteRoute: typeof ProtectedCloudOrganizationSlugProjectRouteRouteWithChildren
}

const ProtectedCloudOrganizationSlugRouteRouteChildren: ProtectedCloudOrganizationSlugRouteRouteChildren =
  {
    ProtectedCloudOrganizationSlugOrgRouteRoute:
      ProtectedCloudOrganizationSlugOrgRouteRouteWithChildren,
    ProtectedCloudOrganizationSlugProjectRouteRoute:
      ProtectedCloudOrganizationSlugProjectRouteRouteWithChildren,
  }

const ProtectedCloudOrganizationSlugRouteRouteWithChildren =
  ProtectedCloudOrganizationSlugRouteRoute._addFileChildren(
    ProtectedCloudOrganizationSlugRouteRouteChildren,
  )

interface ProtectedCloudRouteRouteChildren {
  ProtectedCloudOrganizationSlugRouteRoute: typeof ProtectedCloudOrganizationSlugRouteRouteWithChildren
  ProtectedCloudIndexRoute: typeof ProtectedCloudIndexRoute
}

const ProtectedCloudRouteRouteChildren: ProtectedCloudRouteRouteChildren = {
  ProtectedCloudOrganizationSlugRouteRoute:
    ProtectedCloudOrganizationSlugRouteRouteWithChildren,
  ProtectedCloudIndexRoute: ProtectedCloudIndexRoute,
}

const ProtectedCloudRouteRouteWithChildren =
  ProtectedCloudRouteRoute._addFileChildren(ProtectedCloudRouteRouteChildren)

interface ProtectedRouteRouteChildren {
  ProtectedCloudRouteRoute: typeof ProtectedCloudRouteRouteWithChildren
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedCloudRouteRoute: ProtectedCloudRouteRouteWithChildren,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

interface PublicRouteRouteChildren {
  PublicAuthRoute: typeof PublicAuthRoute
  PublicDocsRoute: typeof PublicDocsRoute
  PublicHomeRoute: typeof PublicHomeRoute
  PublicPricingRoute: typeof PublicPricingRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicAuthRoute: PublicAuthRoute,
  PublicDocsRoute: PublicDocsRoute,
  PublicHomeRoute: PublicHomeRoute,
  PublicPricingRoute: PublicPricingRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface ApiEnrollTokenRouteChildren {
  ApiEnrollTokenCallbackRoute: typeof ApiEnrollTokenCallbackRoute
}

const ApiEnrollTokenRouteChildren: ApiEnrollTokenRouteChildren = {
  ApiEnrollTokenCallbackRoute: ApiEnrollTokenCallbackRoute,
}

const ApiEnrollTokenRouteWithChildren = ApiEnrollTokenRoute._addFileChildren(
  ApiEnrollTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  ApiInngestRoute: ApiInngestRoute,
  ApiWaitlistRoute: ApiWaitlistRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiAuthGithubRoute: ApiAuthGithubRoute,
  ApiEnrollTokenRoute: ApiEnrollTokenRouteWithChildren,
  ApiGithubWebhookRoute: ApiGithubWebhookRoute,
  ApiRuntimeEventsRoute: ApiRuntimeEventsRoute,
  ApiShapesTableRoute: ApiShapesTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
