// Generated by `cargo run -p ployz-sdk-payloads --bin generate-sdk-types`. Do not edit.

export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | JsonObject;

export type JsonObject = { readonly [key: string]: JsonValue | undefined };

export type Additive<T extends object> = T & JsonObject;

export type MachineId = string;

export type ContainerId = string;

export type ServiceName = string;

export type DockerVolumeName = string;

export type CapabilityName = string;

export type MembershipObservation = "unknown" | "up" | "suspect" | "down" | (string & {});

export type HealthObservation = "not_configured" | "starting" | "healthy" | "unhealthy" | (string & {});

export type RpcErrorCode = "invalid_argument" | "not_found" | "ambiguous" | "unsupported" | "unavailable" | "conflict" | "internal" | "unauthenticated" | (string & {});

export type DockerVolumeId = Additive<{
  machine_id: MachineId;
  name: DockerVolumeName;
}>;

export type DockerVolume = Additive<{
  id: DockerVolumeId;
  driver: string;
  options: { readonly [key: string]: string };
  labels: { readonly [key: string]: string };
}>;

export type ContractDescription = Additive<{
  machine_id: MachineId;
  protocol_major: number;
  daemon_version: string;
  capabilities: CapabilityName[];
}>;

export type RpcError = Additive<{
  code: RpcErrorCode;
  message: string;
  details?: JsonValue;
}>;

export type MachineSuccess<T> = Additive<{
  machine_id: MachineId;
  value: T;
}>;

export type MachineFailure<E> = Additive<{
  machine_id: MachineId;
  error: E;
}>;

export type PartialResult<T, E> = Additive<{
  successes: Array<MachineSuccess<T>>;
  failures: Array<MachineFailure<E>>;
  omissions: MachineId[];
}>;

export type ContainerRuntimeObservation =
  | Additive<{ state: "created" }>
  | Additive<{ state: "running"; health: HealthObservation }>
  | Additive<{ state: "paused" }>
  | Additive<{ state: "restarting" }>
  | Additive<{ state: "exited"; code: number }>
  | Additive<{ state: "removing" }>
  | Additive<{ state: "dead" }>
  | Additive<{ state?: string }>;

export type PlanOptions = Additive<{
  force_recreate: boolean;
  skip_health_monitor: boolean;
  placement_seed: number;
}>;

export type ServiceAttempt = Additive<{
  name: ServiceName;
}>;

export type DeployIntent = Additive<{
  target: JsonValue[];
  apply: ServiceAttempt[];
  options: PlanOptions;
}>;

export type DeployOutcome<E = RpcError> =
  | Additive<{ Success: { completed: JsonValue[] } }>
  | Additive<{ Failed: { completed: JsonValue[]; failed: JsonValue; unexecuted: JsonValue[] } }>;

export const GET_CADDY_CONFIG_CAPABILITY: CapabilityName = "ployz.caddy.config.v1";
export const CERTIFICATE_POLICY_CAPABILITY: CapabilityName = "ployz.certificates.policy.v1";
export const CREATE_CONTAINER_CAPABILITY: CapabilityName = "ployz.container.create.v1";
export const EXEC_CONTAINER_CAPABILITY: CapabilityName = "ployz.container.exec.v1";
export const INSPECT_CONTAINER_CAPABILITY: CapabilityName = "ployz.container.inspect.v1";
export const LIST_CONTAINERS_CAPABILITY: CapabilityName = "ployz.container.list.v1";
export const CONTAINER_LOGS_CAPABILITY: CapabilityName = "ployz.container.logs.v1";
export const REMOVE_CONTAINER_CAPABILITY: CapabilityName = "ployz.container.remove.v1";
export const START_CONTAINER_CAPABILITY: CapabilityName = "ployz.container.start.v1";
export const STOP_CONTAINER_CAPABILITY: CapabilityName = "ployz.container.stop.v1";
export const CREATE_DOMAIN_RECORDS_CAPABILITY: CapabilityName = "ployz.dns.records.create.v1";
export const RELEASE_DOMAIN_CAPABILITY: CapabilityName = "ployz.dns.release.v1";
export const RESERVE_DOMAIN_CAPABILITY: CapabilityName = "ployz.dns.reserve.v1";
export const GET_DOMAIN_CAPABILITY: CapabilityName = "ployz.dns.show.v1";
export const ENSURE_IMAGE_INGEST_CAPABILITY: CapabilityName = "ployz.image.ingest.ensure.v1";
export const LIST_IMAGES_CAPABILITY: CapabilityName = "ployz.image.list.v1";
export const PULL_IMAGE_FROM_MACHINE_CAPABILITY: CapabilityName = "ployz.image.pull-from-machine.v1";
export const INITIALIZE_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.initialize.v1";
export const INSPECT_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.inspect.v1";
export const JOIN_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.join.v1";
export const LIST_MACHINES_CAPABILITY: CapabilityName = "ployz.machine.list.v1";
export const MACHINE_LOGS_CAPABILITY: CapabilityName = "ployz.machine.logs.v1";
export const REGISTER_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.register.v1";
export const REMOVE_LOCAL_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.remove-local.v1";
export const REMOVE_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.remove.v1";
export const RESET_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.reset.v1";
export const MACHINE_TOKEN_CAPABILITY: CapabilityName = "ployz.machine.token.v1";
export const UPDATE_MACHINE_CAPABILITY: CapabilityName = "ployz.machine.update.v1";
export const DESCRIBE_CONTRACT_CAPABILITY: CapabilityName = "ployz.rpc.describe-contract.v1";
export const CREATE_VOLUME_CAPABILITY: CapabilityName = "ployz.volume.create.v1";
export const INSPECT_VOLUME_CAPABILITY: CapabilityName = "ployz.volume.inspect.v1";
export const LIST_VOLUMES_CAPABILITY: CapabilityName = "ployz.volume.list.v1";
export const REMOVE_VOLUME_CAPABILITY: CapabilityName = "ployz.volume.remove.v1";
export const INSPECT_WIREGUARD_CAPABILITY: CapabilityName = "ployz.wireguard.inspect.v1";

export const CATALOGUED_CAPABILITIES = [
  "ployz.caddy.config.v1",
  "ployz.certificates.policy.v1",
  "ployz.container.create.v1",
  "ployz.container.exec.v1",
  "ployz.container.inspect.v1",
  "ployz.container.list.v1",
  "ployz.container.logs.v1",
  "ployz.container.remove.v1",
  "ployz.container.start.v1",
  "ployz.container.stop.v1",
  "ployz.dns.records.create.v1",
  "ployz.dns.release.v1",
  "ployz.dns.reserve.v1",
  "ployz.dns.show.v1",
  "ployz.image.ingest.ensure.v1",
  "ployz.image.list.v1",
  "ployz.image.pull-from-machine.v1",
  "ployz.machine.initialize.v1",
  "ployz.machine.inspect.v1",
  "ployz.machine.join.v1",
  "ployz.machine.list.v1",
  "ployz.machine.logs.v1",
  "ployz.machine.register.v1",
  "ployz.machine.remove-local.v1",
  "ployz.machine.remove.v1",
  "ployz.machine.reset.v1",
  "ployz.machine.token.v1",
  "ployz.machine.update.v1",
  "ployz.rpc.describe-contract.v1",
  "ployz.volume.create.v1",
  "ployz.volume.inspect.v1",
  "ployz.volume.list.v1",
  "ployz.volume.remove.v1",
  "ployz.wireguard.inspect.v1",
] as const;

export type CataloguedCapability = (typeof CATALOGUED_CAPABILITIES)[number];

export declare function packageName(): "@ployz/sdk";
