#!/bin/sh
set -eu

unit=unknown
follow=false
while [ "$#" -gt 0 ]; do
    case "$1" in
        -u) unit=$2; shift 2 ;;
        -f) follow=true; shift ;;
        *) shift ;;
    esac
done

emit() {
    printf '%s.000000 %s testkit journal entry\n' "$(date +%s)" "$unit"
}

emit
if [ "$follow" = true ]; then
    while sleep 1; do emit; done
fi
