#!/usr/bin/env bash
# Regenerate the synchronous browser export of the SDK's pure Rust config rules.
set -euo pipefail
repo_dir=$(CDPATH='' cd -- "$(dirname -- "$0")/.." && pwd)
cd "$repo_dir"
wasm_bindgen_version=0.2.127
if [ "$(wasm-bindgen --version 2>/dev/null || true)" != "wasm-bindgen $wasm_bindgen_version" ]; then
  cargo install wasm-bindgen-cli --version "$wasm_bindgen_version" --locked
fi
rustup target add wasm32-unknown-unknown
cargo build -p ployz-config-wasm --release --locked --target wasm32-unknown-unknown
config_build_dir=$(mktemp -d)
trap 'rm -rf "$config_build_dir"' EXIT
wasm-bindgen target/wasm32-unknown-unknown/release/ployz_config_wasm.wasm --out-dir "$config_build_dir" --target web
node - "$config_build_dir" crates/ployz-sdk/generated/config-wasm.mjs <<'NODE'
const fs = require('node:fs');
const [source, destination] = process.argv.slice(2);
const code = fs.readFileSync(`${source}/ployz_config_wasm.js`, 'utf8');
const bytes = fs.readFileSync(`${source}/ployz_config_wasm_bg.wasm`).toString('base64');
// Keep the form API synchronous in both environments, with no fetch during navigation.
fs.writeFileSync(destination, '// Generated by scripts/build-config-browser.sh. Do not edit.\n' + code +
  `\ninitSync({ module: Uint8Array.from(atob('${bytes}'), c => c.charCodeAt(0)) });\n`);
NODE
