use ployz_core::{
    AdvertisedEndpoint, CADDY_VERIFY_PATH, ContainerAddress, ContainerId, ContainerKind,
    ContainerObservation, ContainerRuntimeObservation, HealthObservation, HostBind, HttpProtocol,
    IngressHost, IngressHostname, IssuanceClock, IssuanceFailure, Machine, MachineId, MachineName,
    ManagementAddress, PortPublication, ResolvedServiceSpec, ServiceId, ServiceName,
    TransportProtocol, WireGuardPublicKey, service_containers,
};
use serde_json::json;
use std::collections::BTreeMap;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::sync::Mutex;
use std::time::SystemTime;

use super::{CONFIG_FILE, CaddyAdmin, Error, automatic_caddyfile, generate_caddyfile, reconcile};
use crate::corrosion::{CertificateChallenge, CertificateMaterial, CertificateRow};

#[test]
fn automatic_sites_match_the_frozen_caddyfile_contract() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let remote = MachineId::parse("b".repeat(32)).unwrap();
    let observations = vec![
        observation(
            2,
            &remote,
            "api",
            Some([10, 210, 2, 2]),
            vec![ingress("example.com", 80, HttpProtocol::Http)],
        ),
        observation(
            1,
            &local,
            "api",
            Some([10, 210, 1, 2]),
            vec![
                ingress("example.com", 80, HttpProtocol::Http),
                ingress("secure.example.com", 8443, HttpProtocol::Https),
            ],
        ),
    ];

    assert_eq!(
        automatic_caddyfile(
            &local,
            "node-a",
            &service_containers(observations),
            "TIMESTAMP",
            None,
            &BTreeMap::new(),
        ),
        format!(
            "# Caddyfile autogenerated by Ployz on Machine 'node-a' (DO NOT EDIT): TIMESTAMP\n\
# Automatically updated on Service or health status changes.\n\
# Docs: https://github.com/getployz/ployz2\n\
\n\
{{\n\
\tauto_https off\n\
}}\n\
\n\
# Health check endpoint to verify Caddy reachability on this Machine.\n\
http:// {{\n\
\thandle {CADDY_VERIFY_PATH} {{\n\
\t\trespond \"{local}\" 200\n\
\t}}\n\
\tlog\n\
}}\n\
\n\
(common_proxy) {{\n\
\t# Retry failed requests up to lb_retries times against other available upstreams.\n\
\tlb_retries 3\n\
\t# Upstreams are marked unhealthy for fail_duration after a failed request (passive health checking).\n\
\tfail_duration 30s\n\
}}\n\
\n\
# Sites generated from Service ports.\n\
\n\
http://example.com {{\n\
\treverse_proxy 10.210.1.2:80 10.210.2.2:80 {{\n\
\t\timport common_proxy\n\
\t}}\n\
\tlog\n\
}}\n"
        )
    );
}

#[test]
fn https_site_with_material_pins_tls_paths() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![
            ingress("example.com", 80, HttpProtocol::Http),
            ingress("secure.example.com", 8443, HttpProtocol::Https),
        ],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    let pin = pinned_tls_line(&caddyfile, "secure.example.com").expect("https pin");
    assert!(
        pin.contains("tls /config/certs/secure.example.com-")
            && pin.contains(".crt")
            && pin.contains(".key"),
        "{pin}"
    );
    assert!(caddyfile.contains(&format!(
        "https://secure.example.com {{\n\
{pin}\n\
\treverse_proxy 10.210.1.2:8443 {{\n\
\t\timport common_proxy\n\
\t}}\n\
\tlog\n\
}}\n"
    )));
    assert!(caddyfile.contains(
        "http://example.com {\n\
\treverse_proxy 10.210.1.2:80 {\n\
\t\timport common_proxy\n\
\t}\n\
\tlog\n\
}\n"
    ));
    assert!(!caddyfile.contains("tls /config/certs/example.com"));
}

#[test]
fn changing_material_changes_the_pin_paths() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let containers = service_containers(observations);
    let first = automatic_caddyfile(
        &local,
        "node-a",
        &containers,
        "TIMESTAMP",
        None,
        &BTreeMap::from([(
            IngressHost::parse("secure.example.com").unwrap(),
            CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None),
        )]),
    );
    let second = automatic_caddyfile(
        &local,
        "node-a",
        &containers,
        "TIMESTAMP",
        None,
        &BTreeMap::from([(
            IngressHost::parse("secure.example.com").unwrap(),
            CertificateRow::from_parts(CertificateMaterial::new("CERT-2", "KEY-2"), None),
        )]),
    );

    assert_ne!(
        pinned_tls_line(&first, "secure.example.com"),
        pinned_tls_line(&second, "secure.example.com")
    );
}

#[test]
fn empty_or_absent_material_leaves_today_s_site_bytes() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let containers = service_containers(observations);
    let without = automatic_caddyfile(
        &local,
        "node-a",
        &containers,
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );
    let unused = BTreeMap::from([(
        IngressHost::parse("other.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None),
    )]);

    assert_eq!(
        automatic_caddyfile(
            &local,
            "node-a",
            &containers,
            "TIMESTAMP",
            None,
            &BTreeMap::new(),
        ),
        without
    );
    assert_eq!(
        automatic_caddyfile(&local, "node-a", &containers, "TIMESTAMP", None, &unused,),
        without
    );
    assert!(!without.contains("tls "));
    assert!(!without.contains("https://secure.example.com"));
    assert!(without.contains("auto_https off"));
}

#[test]
fn pending_challenge_is_answered_on_the_http_site() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(None, CertificateChallenge::new("tok", "tok.thumb")),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    assert!(caddyfile.contains("auto_https off"));
    assert!(caddyfile.contains(
        "http://secure.example.com {\n\
\thandle /.well-known/acme-challenge/tok {\n\
\t\trespond \"tok.thumb\" 200\n\
\t}\n\
\tlog\n\
}\n"
    ));
    assert!(!caddyfile.contains("https://secure.example.com"));
}

#[test]
fn last_error_is_a_skipped_certificate_comment() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(None, None).with_backoff(
            "Ingress Hostname secure.example.com resolves to 198.51.100.10; it should resolve to 192.0.2.1.",
            inspect_clock(),
        ),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    assert!(caddyfile.contains(
        "# Skipped certificate issuance:\n\
# - secure.example.com: Ingress Hostname secure.example.com resolves to 198.51.100.10; it should resolve to 192.0.2.1.\n"
    ));
    assert!(!caddyfile.contains("https://secure.example.com"));
}

#[test]
fn last_error_is_omitted_once_material_exists() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None)
            .with_backoff("stale", inspect_clock()),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    assert!(!caddyfile.contains("Skipped certificate issuance"));
    assert!(!caddyfile.contains("stale"));
}

#[test]
fn automatic_sites_exclude_hook_containers() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![
        observation(
            1,
            &local,
            "api",
            Some([10, 210, 1, 2]),
            vec![ingress("api.example", 80, HttpProtocol::Http)],
        ),
        {
            let mut hook = observation(
                2,
                &local,
                "api",
                Some([10, 210, 1, 4]),
                vec![ingress("hook.example", 80, HttpProtocol::Http)],
            );
            hook.kind = ContainerKind::PreDeployHook;
            hook
        },
    ];

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );
    assert!(caddyfile.contains("reverse_proxy 10.210.1.2:80"));
    assert!(!caddyfile.contains("10.210.1.4"));
    assert!(!caddyfile.contains("hook.example"));
}

#[test]
fn automatic_sites_omit_unaddressed_host_and_unassigned_ports() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let ports = vec![
        PortPublication::Host {
            bind: HostBind::All,
            published_port: 80.try_into().unwrap(),
            container_port: 80.try_into().unwrap(),
            transport_protocol: TransportProtocol::Tcp,
        },
        PortPublication::Ingress {
            hostname: IngressHostname::AssignFromClusterDomain,
            load_balancer_port: 80.try_into().unwrap(),
            container_port: 80.try_into().unwrap(),
            http_protocol: HttpProtocol::Http,
        },
    ];
    let observations = [
        observation(
            7,
            &local,
            "missing",
            None,
            vec![ingress("missing.example", 80, HttpProtocol::Http)],
        ),
        observation(8, &local, "transport", Some([10, 210, 1, 8]), ports),
        observation(
            9,
            &local,
            "web",
            Some([10, 210, 1, 9]),
            vec![ingress(
                "web.opaque.uncloud.example",
                8080,
                HttpProtocol::Http,
            )],
        ),
    ];

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );
    assert!(caddyfile.contains(CADDY_VERIFY_PATH));
    assert!(!caddyfile.contains("missing.example"));
    assert!(caddyfile.contains("http://web.opaque.uncloud.example"));
    assert!(caddyfile.contains("reverse_proxy 10.210.1.9:8080"));
    assert!(
        serde_json::from_value::<PortPublication>(json!({
            "mode": "ingress",
            "hostname": { "kind": "explicit", "hostname": "invalid.example" },
            "load_balancer_port": 0,
            "container_port": 0,
            "http_protocol": "http"
        }))
        .is_err()
    );
    assert!(
        serde_json::from_value::<PortPublication>(json!({
            "mode": "ingress",
            "hostname": "",
            "load_balancer_port": 80,
            "container_port": 8080,
            "http_protocol": "http"
        }))
        .is_err()
    );
}

#[tokio::test]
async fn custom_configs_exclude_hook_containers() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let mut hook = custom_observation(
        2,
        9,
        &local,
        "api",
        "hook.example { reverse_proxy {{upstreams}} }",
        [10, 210, 1, 4],
    );
    hook.kind = ContainerKind::PreDeployHook;
    let observations = vec![
        custom_observation(
            1,
            1,
            &local,
            "api",
            "api.example { reverse_proxy {{upstreams}} }",
            [10, 210, 1, 2],
        ),
        hook,
    ];

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        &BTreeMap::new(),
        Some(&FakeAdmin::default()),
    )
    .await;

    assert!(caddyfile.contains(
        "# User-defined config for Service 'api'.\n\
api.example { reverse_proxy 10.210.1.2 }"
    ));
    assert!(!caddyfile.contains("hook.example"));
    assert!(!caddyfile.contains("10.210.1.4"));
}

#[tokio::test]
async fn custom_configs_use_latest_specs_render_upstreams_and_isolate_failures() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let remote = MachineId::parse("b".repeat(32)).unwrap();
    let mut external = custom_observation(
        7,
        1,
        &local,
        "external",
        "external.example { respond external }",
        [10, 210, 1, 7],
    );
    external.address = None;
    let observations = vec![
        custom_observation(
            1,
            1,
            &local,
            "caddy",
            "{\n\tadmin unix/{{upstreams \"api\"}}\n}",
            [10, 210, 1, 1],
        ),
        custom_observation(
            2,
            1,
            &local,
            "api",
            "old.example { respond old }",
            [10, 210, 1, 2],
        ),
        custom_observation(
            3,
            2,
            &remote,
            "api",
            "api.example { reverse_proxy {{upstreams}} }",
            [10, 210, 2, 2],
        ),
        custom_observation(
            4,
            1,
            &local,
            "gateway",
            "gateway.example { reverse_proxy {{upstreams \"api\" 9000}} }",
            [10, 210, 1, 4],
        ),
        custom_observation(
            5,
            1,
            &local,
            "invalid",
            "# invalid\ninvalid.example { respond bad }",
            [10, 210, 1, 5],
        ),
        custom_observation(
            6,
            1,
            &local,
            "web",
            "web.example { reverse_proxy {{upstreams 8080}} }",
            [10, 210, 1, 6],
        ),
        external,
    ];
    let admin = FakeAdmin::default();

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        &BTreeMap::new(),
        Some(&admin),
    )
    .await;

    assert!(caddyfile.starts_with(
        "# Caddyfile autogenerated by Ployz on Machine 'node-a' (DO NOT EDIT): TIMESTAMP\n\
# Automatically updated on Service or health status changes.\n\
# Docs: https://github.com/getployz/ployz2\n\
\n\
# User-defined global config from Service 'caddy'.\n\
{\n\tauto_https off\n\tadmin unix/10.210.1.2 10.210.2.2\n}\n\n"
    ));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'api'.\n\
api.example { reverse_proxy 10.210.1.2 10.210.2.2 }"
    ));
    assert!(!caddyfile.contains("old.example"));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'gateway'.\n\
gateway.example { reverse_proxy 10.210.1.2:9000 10.210.2.2:9000 }"
    ));
    assert!(caddyfile.contains(
        "# Skipped invalid user-defined configs:\n\
# - Service 'invalid': validation failed: invalid config detected\n"
    ));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'web'.\n\
web.example { reverse_proxy 10.210.1.6:8080 }"
    ));
    assert!(caddyfile.contains("external.example { respond external }"));
    assert_eq!(admin.adapted.lock().unwrap().len(), 6);
}

#[tokio::test]
async fn unavailable_caddy_omits_every_custom_config() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = [custom_observation(
        1,
        1,
        &local,
        "api",
        "custom.example { respond custom }",
        [10, 210, 1, 1],
    )];

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIME",
        &BTreeMap::new(),
        None::<&FakeAdmin>,
    )
    .await;
    assert!(!caddyfile.contains("custom.example"));
    assert!(caddyfile.contains("admin API is not reachable"));
}

#[tokio::test]
async fn broken_global_template_does_not_hide_valid_service_configs() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = [
        custom_observation(
            1,
            1,
            &local,
            "caddy",
            "{{unknown\ninjected.example { respond owned }\n}}",
            [10, 210, 1, 1],
        ),
        custom_observation(
            2,
            1,
            &local,
            "api",
            "api.example { respond ok }",
            [10, 210, 1, 2],
        ),
    ];

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIME",
        &BTreeMap::new(),
        Some(&FakeAdmin::default()),
    )
    .await;
    assert!(caddyfile.contains("Service 'caddy': rendering failed"));
    assert!(caddyfile.contains("#   injected.example { respond owned }"));
    assert!(
        !caddyfile
            .lines()
            .any(|line| line.starts_with("injected.example"))
    );
    assert!(caddyfile.contains("api.example { respond ok }"));
}

#[tokio::test]
async fn failed_load_preserves_the_last_caddyfile() {
    let directory =
        std::env::temp_dir().join(format!("ployz-caddy-load-test-{}", std::process::id()));
    let path = directory.join(CONFIG_FILE);
    std::fs::create_dir_all(&directory).unwrap();
    std::fs::write(&path, "last loaded").unwrap();
    let machine = Machine {
        id: MachineId::parse("a".repeat(32)).unwrap(),
        name: MachineName::parse("node-a").unwrap(),
        subnet: "10.210.1.0/24".parse().unwrap(),
        management_address: ManagementAddress("fdcc::1".parse().unwrap()),
        public_key: WireGuardPublicKey([1; 32]),
        public_ip: None,
        advertised_endpoints: vec![AdvertisedEndpoint("192.0.2.1:51000".parse().unwrap())],
        runtime: Default::default(),
    };
    let admin = FakeAdmin {
        fail_load: true,
        ..FakeAdmin::default()
    };

    assert!(
        reconcile(&machine, &[], &BTreeMap::new(), &path, Some(&admin),)
            .await
            .is_err()
    );
    assert_eq!(std::fs::read_to_string(&path).unwrap(), "last loaded");
    std::fs::remove_dir_all(directory).unwrap();
}

#[tokio::test]
async fn reconcile_writes_material_and_pins_it_before_load() {
    let directory =
        std::env::temp_dir().join(format!("ployz-caddy-cert-test-{}", std::process::id()));
    let path = directory.join(CONFIG_FILE);
    std::fs::create_dir_all(&directory).unwrap();
    let machine = Machine {
        id: MachineId::parse("a".repeat(32)).unwrap(),
        name: MachineName::parse("node-a").unwrap(),
        subnet: "10.210.1.0/24".parse().unwrap(),
        management_address: ManagementAddress("fdcc::1".parse().unwrap()),
        public_key: WireGuardPublicKey([1; 32]),
        public_ip: None,
        advertised_endpoints: vec![AdvertisedEndpoint("192.0.2.1:51000".parse().unwrap())],
        runtime: Default::default(),
    };
    let observations = [observation(
        1,
        &machine.id,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT-BODY", "KEY-BODY"), None),
    )]);
    let admin = FakeAdmin::default();
    let certs = directory.join("certs");
    std::fs::create_dir_all(&certs).unwrap();
    let stale_cert = certs.join("secure.example.com-old.crt");
    let stale_key = certs.join("secure.example.com-old.key");
    std::fs::write(&stale_cert, "OLD").unwrap();
    std::fs::write(&stale_key, "OLD").unwrap();

    reconcile(&machine, &observations, &certificates, &path, Some(&admin))
        .await
        .unwrap();

    let caddyfile = std::fs::read_to_string(&path).unwrap();
    let pin = pinned_tls_line(&caddyfile, "secure.example.com").expect("https pin");
    let (cert_name, key_name) = pinned_file_names(pin);
    let cert = certs.join(&cert_name);
    let key = certs.join(&key_name);
    assert_eq!(std::fs::read_to_string(&cert).unwrap(), "CERT-BODY");
    assert_eq!(std::fs::read_to_string(&key).unwrap(), "KEY-BODY");
    assert_eq!(
        std::fs::metadata(&key).unwrap().permissions().mode() & 0o777,
        0o600
    );
    assert!(!stale_cert.exists());
    assert!(!stale_key.exists());
    let adapted = admin.adapted.lock().unwrap();
    assert!(
        adapted
            .last()
            .is_some_and(|config| config.contains(&format!("tls /config/certs/{cert_name}")))
    );
    std::fs::remove_dir_all(directory).unwrap();
}

fn pinned_tls_line<'a>(caddyfile: &'a str, hostname: &str) -> Option<&'a str> {
    let needle = format!("tls /config/certs/{hostname}-");
    caddyfile.lines().find(|line| line.contains(&needle))
}

fn pinned_file_names(pin: &str) -> (String, String) {
    let mut paths = pin.split_whitespace().skip(1);
    let cert = paths.next().expect("cert path");
    let key = paths.next().expect("key path");
    (
        Path::new(cert)
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .to_owned(),
        Path::new(key)
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .to_owned(),
    )
}

#[derive(Default)]
struct FakeAdmin {
    adapted: Mutex<Vec<String>>,
    fail_load: bool,
}

impl CaddyAdmin for FakeAdmin {
    async fn adapt(&self, caddyfile: &str) -> Result<String, Error> {
        self.adapted.lock().unwrap().push(caddyfile.into());
        if caddyfile.contains("# invalid") {
            Err(Error::Admin("invalid config detected".into()))
        } else {
            Ok("{}".into())
        }
    }

    async fn load(&self, _json: &str) -> Result<(), Error> {
        if self.fail_load {
            Err(Error::Admin("load failed".into()))
        } else {
            Ok(())
        }
    }
}

fn inspect_clock() -> IssuanceClock {
    IssuanceClock::new(
        1,
        SystemTime::UNIX_EPOCH,
        IssuanceFailure::ResolvesElsewhere,
    )
}

fn ingress(hostname: &str, port: u16, http_protocol: HttpProtocol) -> PortPublication {
    PortPublication::Ingress {
        hostname: IngressHostname::explicit(hostname).unwrap(),
        load_balancer_port: port.try_into().unwrap(),
        container_port: port.try_into().unwrap(),
        http_protocol,
    }
}

fn observation(
    suffix: u8,
    machine_id: &MachineId,
    service_name: &str,
    address: Option<[u8; 4]>,
    ports: Vec<PortPublication>,
) -> ContainerObservation {
    let service_id = ServiceId::parse(format!("{suffix:x}").repeat(32)).unwrap();
    let service_name = ServiceName::parse(service_name).unwrap();
    let resolved_spec: ResolvedServiceSpec = serde_json::from_value(json!({
        "service_id": service_id,
        "name": service_name,
        "mode": { "mode": "replicated", "replicas": 1 },
        "container": { "image": "example.test/image", "pull_policy": "missing" },
        "ports": ports,
    }))
    .unwrap();
    ContainerObservation {
        container_id: ContainerId::parse(format!("{suffix:x}").repeat(64)).unwrap(),
        display_name: format!("{service_name}-{suffix}"),
        created_at_unix_nanos: 0,
        machine_id: *machine_id,
        service_id,
        service_name,
        kind: ContainerKind::ServiceContainer,
        runtime: ContainerRuntimeObservation::Running {
            health: HealthObservation::Healthy,
        },
        effective_healthcheck: None,
        resolved_spec,
        address: address.map(|address| ContainerAddress(address.into())),
        labels: BTreeMap::new(),
    }
}

fn custom_observation(
    suffix: u8,
    created_at_unix_nanos: i64,
    machine_id: &MachineId,
    service_name: &str,
    caddy_config: &str,
    address: [u8; 4],
) -> ContainerObservation {
    let mut observation = observation(suffix, machine_id, service_name, Some(address), Vec::new());
    observation.created_at_unix_nanos = created_at_unix_nanos;
    observation.resolved_spec.caddy_config = Some(caddy_config.into());
    observation
}
