use super::{
    CONFIG_FILE, CaddyAdmin, Error, automatic_caddyfile as render_automatic_caddyfile,
    generate_caddyfile as render_caddyfile,
};
use crate::{
    corrosion::{CertificateChallenge, CertificateMaterial, CertificateRow},
    ingress::{IngressProjection, apply_caddy, tests::renderer_projection},
};
use ployz_core::{
    AdvertisedEndpoint, ContainerAddress, ContainerId, ContainerKind, ContainerObservation,
    ContainerRuntimeObservation, HealthObservation, HostBind, HttpProtocol, INGRESS_VERIFY_PATH,
    IngressHost, IngressHostname, IngressProxyFragment, MACHINE_API_PORT, Machine, MachineId,
    MachineName, PortPublication, ProjectName, QualifiedService, ResolvedServiceSpec,
    ServiceContainer, ServiceId, ServiceName, TransportProtocol, WireGuardPublicKey,
    service_containers,
};
use serde_json::json;
use std::collections::BTreeMap;
use std::os::unix::fs::PermissionsExt;
use std::path::Path;
use std::sync::Mutex;

#[path = "caddy_tests/watcher.rs"]
mod watcher;

fn projection(
    local_machine: &MachineId,
    machine_name: &str,
    containers: &[ServiceContainer],
    certificates: &BTreeMap<IngressHost, CertificateRow>,
) -> IngressProjection {
    let machine = Machine {
        id: *local_machine,
        name: MachineName::parse(machine_name).unwrap(),
        subnet: "10.210.1.0/24".parse().unwrap(),
        public_key: WireGuardPublicKey([1; 32]),
        public_ip: None,
        advertised_endpoints: Vec::new(),
        runtime: Default::default(),
    };
    IngressProjection::derive(
        &machine,
        &containers
            .iter()
            .cloned()
            .map(ServiceContainer::into_observation)
            .collect::<Vec<_>>(),
        certificates,
    )
}

fn automatic_caddyfile(
    local_machine: &MachineId,
    machine_name: &str,
    containers: &[ServiceContainer],
    timestamp: &str,
    global_config: Option<&str>,
    certificates: &BTreeMap<IngressHost, CertificateRow>,
) -> String {
    render_automatic_caddyfile(
        &projection(local_machine, machine_name, containers, certificates),
        timestamp,
        global_config,
    )
}

async fn generate_caddyfile<A: CaddyAdmin>(
    local_machine: &MachineId,
    machine_name: &str,
    containers: &[ServiceContainer],
    timestamp: &str,
    certificates: &BTreeMap<IngressHost, CertificateRow>,
    admin: Option<&A>,
) -> String {
    render_caddyfile(
        &projection(local_machine, machine_name, containers, certificates),
        timestamp,
        admin,
    )
    .await
}

async fn reconcile<A: CaddyAdmin>(
    machine: &Machine,
    observations: &[ContainerObservation],
    certificates: &BTreeMap<IngressHost, CertificateRow>,
    config_file: &Path,
    admin: Option<&A>,
) -> Result<(), Error> {
    let projection = IngressProjection::derive(machine, observations, certificates);
    apply_caddy(&projection, config_file, admin).await
}

#[test]
fn automatic_sites_match_the_frozen_caddyfile_contract() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let remote = MachineId::parse("b".repeat(32)).unwrap();
    let observations = vec![
        observation(
            2,
            &remote,
            "api",
            Some([10, 210, 2, 2]),
            vec![ingress("example.com", 80, HttpProtocol::Http)],
        ),
        observation(
            1,
            &local,
            "api",
            Some([10, 210, 1, 2]),
            vec![ingress("example.com", 80, HttpProtocol::Http)],
        ),
    ];

    assert_eq!(
        automatic_caddyfile(
            &local,
            "node-a",
            &service_containers(observations),
            "TIMESTAMP",
            None,
            &BTreeMap::new(),
        ),
        format!(
            "# Caddyfile autogenerated by Ployz on Machine 'node-a' (DO NOT EDIT): TIMESTAMP\n\
# Automatically updated on Service or health status changes.\n\
# Docs: https://github.com/getployz/ployz2\n\
\n\
{{\n\
\tauto_https off\n\
}}\n\
\n\
# Health check endpoint to verify Caddy reachability on this Machine.\n\
http:// {{\n\
\thandle {INGRESS_VERIFY_PATH} {{\n\
\t\trespond \"{local}\" 200\n\
\t}}\n\
\trespond \"Not Found\" 404\n\
\tlog\n\
}}\n\
\n\
(common_proxy) {{\n\
\t# Retry failed requests up to lb_retries times against other available upstreams.\n\
\tlb_retries 3\n\
\t# Upstreams are marked unhealthy for fail_duration after a failed request (passive health checking).\n\
\tfail_duration 30s\n\
}}\n\
\n\
# Sites generated from Service ports.\n\
\n\
http://example.com {{\n\
\treverse_proxy 10.210.1.2:80 10.210.2.2:80 {{\n\
\t\timport common_proxy\n\
\t}}\n\
\tlog\n\
}}\n"
        )
    );
}

#[test]
fn shared_renderer_projection_drives_caddy() {
    let caddyfile = render_automatic_caddyfile(&renderer_projection(), "TIMESTAMP", None);

    assert!(caddyfile.contains("http://empty.example.com {\n\trespond \"Bad Gateway\" 502"));
    assert!(
        caddyfile.contains("reverse_proxy 10.210.1.2:8080 10.210.2.2:8080"),
        "{caddyfile}"
    );
    assert!(
        caddyfile.contains(
            "tls /config/caddy/certs/secure.example.com-1d660d5cdaeaac5dcae6e864c8ee63cd0a4483556f2e1d3bf8d66b2e8bc74e67.crt /config/caddy/certs/secure.example.com-1d660d5cdaeaac5dcae6e864c8ee63cd0a4483556f2e1d3bf8d66b2e8bc74e67.key"
        ),
        "{caddyfile}"
    );
}

#[test]
fn projection_resolves_route_endpoints_certificate_and_tagged_fragment() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let remote = MachineId::parse("b".repeat(32)).unwrap();
    let mut local_container = observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("example.com", 8080, HttpProtocol::Http)],
    );
    local_container
        .try_update(|parts| parts.created_at_unix_nanos = 1)
        .unwrap();
    let fragment = IngressProxyFragment::parse_caddy("# selected").unwrap();
    local_container
        .try_update(|parts| parts.resolved_spec.ingress_proxy_fragment = Some(fragment.clone()))
        .unwrap();
    let mut remote_container = observation(
        2,
        &remote,
        "api",
        Some([10, 210, 2, 2]),
        vec![ingress("example.com", 8080, HttpProtocol::Http)],
    );
    remote_container
        .try_update(|parts| {
            parts.created_at_unix_nanos = 2;
            parts.resolved_spec.ingress_proxy_fragment = Some(fragment.clone());
        })
        .unwrap();
    let material = CertificateMaterial::new("CERT", "KEY").unwrap();
    let challenge = CertificateChallenge::new("token", "response").unwrap();
    let certificates = BTreeMap::from([(
        IngressHost::parse("example.com").unwrap(),
        CertificateRow::from_parts(Some(material.clone()), Some(challenge.clone())),
    )]);

    let projection = projection(
        &local,
        "node-a",
        &service_containers([remote_container, local_container]),
        &certificates,
    );

    let site = projection.sites.first().unwrap();
    let publication = site.publication.as_ref().unwrap();
    assert_eq!(site.hostname.as_str(), "example.com");
    assert_eq!(publication.owner.to_string(), "app/api");
    assert!(publication.https.is_none());
    assert_eq!(
        publication
            .http
            .as_ref()
            .unwrap()
            .iter()
            .map(|endpoint| (endpoint.address.0, endpoint.port.get()))
            .collect::<Vec<_>>(),
        [
            ("10.210.1.2".parse().unwrap(), 8080),
            ("10.210.2.2".parse().unwrap(), 8080)
        ]
    );
    assert_eq!(
        projection
            .service_fragments
            .get(&QualifiedService::parse("app/api").unwrap()),
        Some(&fragment)
    );
    let certificate = site.certificate.as_ref().unwrap();
    assert_eq!(certificate.challenge.as_ref(), Some(&challenge));
    assert_eq!(certificate.material.as_ref(), Some(&material));
}

#[test]
fn unrelated_unfragmented_service_does_not_change_the_ingress_projection() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let empty = projection(&local, "node-a", &[], &BTreeMap::new());
    let unrelated = service_containers([observation(
        1,
        &local,
        "worker",
        Some([10, 210, 1, 2]),
        Vec::new(),
    )]);

    assert_eq!(
        projection(&local, "node-a", &unrelated, &BTreeMap::new()),
        empty
    );
}

#[test]
fn contested_custom_hostname_keeps_one_qualified_service_upstream_set() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let mut shop_old = observation(
        1,
        &local,
        "web",
        Some([10, 210, 1, 2]),
        vec![ingress("api.example.com", 80, HttpProtocol::Http)],
    );
    shop_old
        .try_update(|parts| {
            parts.project_name = ProjectName::parse("shop").unwrap();
            parts.created_at_unix_nanos = 1;
        })
        .unwrap();
    let mut shop_rollout = observation(
        3,
        &local,
        "web",
        Some([10, 210, 1, 3]),
        vec![ingress("api.example.com", 80, HttpProtocol::Http)],
    );
    shop_rollout
        .try_update(|parts| {
            parts.project_name = ProjectName::parse("shop").unwrap();
            parts.created_at_unix_nanos = 3;
        })
        .unwrap();
    let mut blog = observation(
        2,
        &local,
        "web",
        Some([10, 210, 2, 2]),
        vec![ingress("api.example.com", 80, HttpProtocol::Http)],
    );
    blog.try_update(|parts| {
        parts.project_name = ProjectName::parse("blog").unwrap();
        parts.created_at_unix_nanos = 2;
    })
    .unwrap();

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(vec![blog, shop_rollout, shop_old]),
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );

    assert!(
        caddyfile.contains("reverse_proxy 10.210.1.2:80 10.210.1.3:80"),
        "{caddyfile}"
    );
    assert!(
        !caddyfile.contains("10.210.2.2"),
        "loser must not join the winner's upstream pool: {caddyfile}"
    );
    assert_eq!(
        caddyfile.matches("http://api.example.com").count(),
        1,
        "{caddyfile}"
    );
}

#[test]
fn proxy_owner_may_disagree_across_observation_sets_and_converges_when_they_match() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let mut shop = observation(
        1,
        &local,
        "web",
        Some([10, 210, 1, 2]),
        vec![ingress("api.example.com", 80, HttpProtocol::Http)],
    );
    shop.try_update(|parts| {
        parts.project_name = ProjectName::parse("shop").unwrap();
        parts.created_at_unix_nanos = 1;
    })
    .unwrap();
    let mut blog = observation(
        2,
        &local,
        "web",
        Some([10, 210, 2, 2]),
        vec![ingress("api.example.com", 80, HttpProtocol::Http)],
    );
    blog.try_update(|parts| {
        parts.project_name = ProjectName::parse("blog").unwrap();
        parts.created_at_unix_nanos = 2;
    })
    .unwrap();

    let file = |observations: Vec<ContainerObservation>| {
        automatic_caddyfile(
            &local,
            "node-a",
            &service_containers(observations),
            "TIMESTAMP",
            None,
            &BTreeMap::new(),
        )
    };
    let shop_only = file(vec![shop.clone()]);
    let blog_only = file(vec![blog.clone()]);
    assert!(shop_only.contains("10.210.1.2:80"), "{shop_only}");
    assert!(!shop_only.contains("10.210.2.2"), "{shop_only}");
    assert!(blog_only.contains("10.210.2.2:80"), "{blog_only}");
    assert!(!blog_only.contains("10.210.1.2"), "{blog_only}");
    assert_ne!(shop_only, blog_only);

    let together = file(vec![blog.clone(), shop.clone()]);
    let together_again = file(vec![shop, blog]);
    assert_eq!(together, together_again);
    assert!(together.contains("10.210.1.2:80"), "{together}");
    assert!(!together.contains("10.210.2.2"), "{together}");
}

#[test]
fn https_site_with_material_pins_tls_paths() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![
            ingress("example.com", 80, HttpProtocol::Http),
            ingress("secure.example.com", 8443, HttpProtocol::Https),
        ],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    let pin = pinned_tls_line(&caddyfile, "secure.example.com").expect("https pin");
    assert!(
        pin.contains("tls /config/caddy/certs/secure.example.com-")
            && pin.contains(".crt")
            && pin.contains(".key"),
        "{pin}"
    );
    assert!(caddyfile.contains(&format!(
        "https://secure.example.com {{\n\
{pin}\n\
\treverse_proxy 10.210.1.2:8443 {{\n\
\t\timport common_proxy\n\
\t}}\n\
\tlog\n\
}}\n"
    )));
    assert!(caddyfile.contains(
        "http://example.com {\n\
\treverse_proxy 10.210.1.2:80 {\n\
\t\timport common_proxy\n\
\t}\n\
\tlog\n\
}\n"
    ));
    assert!(!caddyfile.contains("tls /config/caddy/certs/example.com"));
}

#[test]
fn changing_material_changes_the_pin_paths() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let containers = service_containers(observations);
    let first = automatic_caddyfile(
        &local,
        "node-a",
        &containers,
        "TIMESTAMP",
        None,
        &BTreeMap::from([(
            IngressHost::parse("secure.example.com").unwrap(),
            CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None),
        )]),
    );
    let second = automatic_caddyfile(
        &local,
        "node-a",
        &containers,
        "TIMESTAMP",
        None,
        &BTreeMap::from([(
            IngressHost::parse("secure.example.com").unwrap(),
            CertificateRow::from_parts(CertificateMaterial::new("CERT-2", "KEY-2"), None),
        )]),
    );

    assert_ne!(
        pinned_tls_line(&first, "secure.example.com"),
        pinned_tls_line(&second, "secure.example.com")
    );
}

#[test]
fn empty_or_absent_material_leaves_today_s_site_bytes() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let containers = service_containers(observations);
    let without = automatic_caddyfile(
        &local,
        "node-a",
        &containers,
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );
    let unused = BTreeMap::from([(
        IngressHost::parse("other.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None),
    )]);

    assert_eq!(
        automatic_caddyfile(
            &local,
            "node-a",
            &containers,
            "TIMESTAMP",
            None,
            &BTreeMap::new(),
        ),
        without
    );
    assert_eq!(
        automatic_caddyfile(&local, "node-a", &containers, "TIMESTAMP", None, &unused,),
        without
    );
    assert!(!without.contains("tls "));
    assert!(!without.contains("https://secure.example.com"));
    assert!(without.contains("auto_https off"));
}

#[test]
fn pending_challenge_is_answered_on_the_http_site() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(None, CertificateChallenge::new("tok", "tok.thumb")),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    assert!(caddyfile.contains("auto_https off"));
    assert!(caddyfile.contains(
        "http://secure.example.com {\n\
\thandle /.well-known/acme-challenge/tok {\n\
\t\trespond \"tok.thumb\" 200\n\
\t}\n\
\trespond \"Bad Gateway\" 502\n\
\tlog\n\
}\n"
    ));
    assert!(!caddyfile.contains("https://secure.example.com"));
}

#[test]
fn last_error_is_a_skipped_certificate_comment() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(None, None).with_error(
            "Ingress Hostname secure.example.com resolves to 198.51.100.10; it should resolve to 192.0.2.1.",
        ),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    assert!(caddyfile.contains(
        "# Skipped certificate issuance:\n\
# - secure.example.com: Ingress Hostname secure.example.com resolves to 198.51.100.10; it should resolve to 192.0.2.1.\n"
    ));
    assert!(!caddyfile.contains("https://secure.example.com"));
}

#[test]
fn last_error_is_omitted_once_material_exists() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![observation(
        1,
        &local,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT", "KEY"), None)
            .with_error("stale"),
    )]);

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &certificates,
    );

    assert!(!caddyfile.contains("Skipped certificate issuance"));
    assert!(!caddyfile.contains("stale"));
}

#[test]
fn automatic_sites_exclude_hook_containers() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = vec![
        observation(
            1,
            &local,
            "api",
            Some([10, 210, 1, 2]),
            vec![ingress("api.example", 80, HttpProtocol::Http)],
        ),
        {
            let mut hook = observation(
                2,
                &local,
                "api",
                Some([10, 210, 1, 4]),
                vec![ingress("hook.example", 80, HttpProtocol::Http)],
            );
            hook.try_update(|parts| parts.kind = ContainerKind::PreDeployHook)
                .unwrap();
            hook
        },
    ];

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );
    assert!(caddyfile.contains("reverse_proxy 10.210.1.2:80"));
    assert!(!caddyfile.contains("10.210.1.4"));
    assert!(!caddyfile.contains("hook.example"));
}

#[test]
fn automatic_sites_keep_unreachable_hosts_and_omit_unassigned_ports() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let ports = vec![
        PortPublication::Host {
            bind: HostBind::All,
            published_port: 80.try_into().unwrap(),
            container_port: 80.try_into().unwrap(),
            transport_protocol: TransportProtocol::Tcp,
        },
        PortPublication::Ingress {
            hostname: IngressHostname::cluster_domain(),
            load_balancer_port: 80.try_into().unwrap(),
            container_port: 80.try_into().unwrap(),
            http_protocol: HttpProtocol::Http,
        },
        PortPublication::Ingress {
            hostname: IngressHostname::cluster_domain_label("api").unwrap(),
            load_balancer_port: 80.try_into().unwrap(),
            container_port: 80.try_into().unwrap(),
            http_protocol: HttpProtocol::Http,
        },
    ];
    let observations = [
        observation(
            7,
            &local,
            "missing",
            None,
            vec![ingress("missing.example", 80, HttpProtocol::Http)],
        ),
        observation(8, &local, "transport", Some([10, 210, 1, 8]), ports),
        observation(
            9,
            &local,
            "web",
            Some([10, 210, 1, 9]),
            vec![ingress(
                "web.opaque.ployz.example",
                8080,
                HttpProtocol::Http,
            )],
        ),
    ];

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );
    assert!(caddyfile.contains(INGRESS_VERIFY_PATH));
    assert!(caddyfile.contains(
        "http://missing.example {\n\
\trespond \"Bad Gateway\" 502\n\
\tlog\n\
}\n"
    ));
    assert!(caddyfile.contains("http://web.opaque.ployz.example"));
    assert!(caddyfile.contains("reverse_proxy 10.210.1.9:8080"));
    assert!(
        serde_json::from_value::<PortPublication>(json!({
            "mode": "ingress",
            "hostname": { "kind": "explicit", "hostname": "invalid.example" },
            "load_balancer_port": 0,
            "container_port": 0,
            "http_protocol": "http"
        }))
        .is_err()
    );
    assert!(
        serde_json::from_value::<PortPublication>(json!({
            "mode": "ingress",
            "hostname": "",
            "load_balancer_port": 80,
            "container_port": 8080,
            "http_protocol": "http"
        }))
        .is_err()
    );
}

#[test]
fn published_hosts_without_healthy_replicas_return_bad_gateway() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let healthy = observation(
        1,
        &local,
        "healthy",
        Some([10, 210, 1, 2]),
        vec![ingress("healthy.example", 80, HttpProtocol::Http)],
    );
    let mut stopped = observation(
        2,
        &local,
        "stopped",
        Some([10, 210, 1, 3]),
        vec![ingress("stopped.example", 80, HttpProtocol::Http)],
    );
    stopped
        .try_update(|parts| parts.runtime = ContainerRuntimeObservation::Exited { code: 137 })
        .unwrap();
    let mut unhealthy = observation(
        3,
        &local,
        "unhealthy",
        Some([10, 210, 1, 4]),
        vec![ingress("unhealthy.example", 80, HttpProtocol::Http)],
    );
    unhealthy
        .try_update(|parts| {
            parts.runtime = ContainerRuntimeObservation::Running {
                health: HealthObservation::Unhealthy,
            }
        })
        .unwrap();

    let caddyfile = automatic_caddyfile(
        &local,
        "node-a",
        &service_containers([healthy, stopped, unhealthy]),
        "TIMESTAMP",
        None,
        &BTreeMap::new(),
    );

    assert!(caddyfile.contains(
        "http://healthy.example {\n\
\treverse_proxy 10.210.1.2:80"
    ));
    for hostname in ["stopped.example", "unhealthy.example"] {
        assert!(caddyfile.contains(&format!(
            "http://{hostname} {{\n\
\trespond \"Bad Gateway\" 502\n\
\tlog\n\
}}\n"
        )));
    }
    assert!(!caddyfile.contains("unknown Host"));
}

#[tokio::test]
async fn custom_configs_exclude_hook_containers() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let mut hook = custom_observation(
        2,
        9,
        &local,
        "api",
        "hook.example { reverse_proxy {{upstreams}} }",
        [10, 210, 1, 4],
    );
    hook.try_update(|parts| parts.kind = ContainerKind::PreDeployHook)
        .unwrap();
    let observations = vec![
        custom_observation(
            1,
            1,
            &local,
            "api",
            "api.example { reverse_proxy {{upstreams}} }",
            [10, 210, 1, 2],
        ),
        hook,
    ];

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        &BTreeMap::new(),
        Some(&FakeAdmin::default()),
    )
    .await;

    assert!(caddyfile.contains(
        "# User-defined config for Service 'app/api'.\n\
api.example { reverse_proxy 10.210.1.2 }"
    ));
    assert!(!caddyfile.contains("hook.example"));
    assert!(!caddyfile.contains("10.210.1.4"));
}

#[tokio::test]
async fn user_project_caddy_does_not_supply_global_config() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let mut user = custom_observation(2, 9, &local, "caddy", "{\n\tadmin off\n}", [10, 210, 1, 9]);
    user.try_update(|parts| parts.project_name = ployz_core::ProjectName::parse("shop").unwrap())
        .unwrap();
    let observations = vec![
        reserved(observation(
            1,
            &local,
            "ingress",
            Some([10, 210, 1, 1]),
            Vec::new(),
        )),
        user,
    ];

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        &BTreeMap::new(),
        Some(&FakeAdmin::default()),
    )
    .await;

    assert!(!caddyfile.contains("User-defined global config from Service 'caddy'"));
}

#[tokio::test]
async fn custom_configs_use_latest_specs_render_upstreams_and_isolate_failures() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let remote = MachineId::parse("b".repeat(32)).unwrap();
    let mut external = custom_observation(
        7,
        1,
        &local,
        "external",
        "external.example { respond external }",
        [10, 210, 1, 7],
    );
    external.try_update(|parts| parts.address = None).unwrap();
    let observations = vec![
        reserved(custom_observation(
            1,
            1,
            &local,
            "ingress",
            "{\n\tadmin unix/{{upstreams \"app/api\"}}\n}",
            [10, 210, 1, 1],
        )),
        custom_observation(
            2,
            1,
            &local,
            "api",
            "old.example { respond old }",
            [10, 210, 1, 2],
        ),
        custom_observation(
            3,
            2,
            &remote,
            "api",
            "api.example { reverse_proxy {{upstreams}} }",
            [10, 210, 2, 2],
        ),
        custom_observation(
            4,
            1,
            &local,
            "gateway",
            "gateway.example { reverse_proxy {{upstreams \"api\" 9000}} }",
            [10, 210, 1, 4],
        ),
        custom_observation(
            5,
            1,
            &local,
            "invalid",
            "# invalid\ninvalid.example { respond bad }",
            [10, 210, 1, 5],
        ),
        custom_observation(
            6,
            1,
            &local,
            "web",
            "web.example { reverse_proxy {{upstreams 8080}} }",
            [10, 210, 1, 6],
        ),
        external,
    ];
    let admin = FakeAdmin::default();

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        &BTreeMap::new(),
        Some(&admin),
    )
    .await;

    assert!(caddyfile.starts_with(
        "# Caddyfile autogenerated by Ployz on Machine 'node-a' (DO NOT EDIT): TIMESTAMP\n\
# Automatically updated on Service or health status changes.\n\
# Docs: https://github.com/getployz/ployz2\n\
\n\
# User-defined global config from Service 'ployz-system/ingress'.\n\
{\n\tauto_https off\n\tadmin unix/10.210.2.2\n}\n\n"
    ));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'app/api'.\n\
api.example { reverse_proxy 10.210.2.2 }"
    ));
    assert!(!caddyfile.contains("old.example"));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'app/gateway'.\n\
gateway.example { reverse_proxy 10.210.2.2:9000 }"
    ));
    assert!(caddyfile.contains(
        "# Skipped invalid user-defined configs:\n\
# - Service 'app/invalid': validation failed: invalid config detected\n"
    ));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'app/web'.\n\
web.example { reverse_proxy 10.210.1.6:8080 }"
    ));
    assert!(caddyfile.contains("external.example { respond external }"));
    assert_eq!(admin.adapted.lock().unwrap().len(), 6);
}

#[tokio::test]
async fn custom_upstream_short_names_do_not_cross_projects() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let mut staging_web = custom_observation(
        2,
        1,
        &local,
        "web",
        "staging.example { reverse_proxy {{upstreams \"api\"}} }",
        [10, 210, 1, 2],
    );
    staging_web
        .try_update(|parts| parts.project_name = ProjectName::parse("shop-staging").unwrap())
        .unwrap();
    let mut prod_api = custom_observation(
        3,
        1,
        &local,
        "api",
        "api.example { respond api }",
        [10, 210, 1, 11],
    );
    prod_api
        .try_update(|parts| parts.project_name = ProjectName::parse("shop-prod").unwrap())
        .unwrap();
    let mut prod_web = custom_observation(
        4,
        1,
        &local,
        "web",
        "prod.example { reverse_proxy {{upstreams \"api\"}} }",
        [10, 210, 1, 3],
    );
    prod_web
        .try_update(|parts| parts.project_name = ProjectName::parse("shop-prod").unwrap())
        .unwrap();
    let mut staging_other = custom_observation(
        5,
        1,
        &local,
        "other",
        "cross.example { reverse_proxy {{upstreams \"shop-prod/api\"}} }",
        [10, 210, 1, 4],
    );
    staging_other
        .try_update(|parts| parts.project_name = ProjectName::parse("shop-staging").unwrap())
        .unwrap();
    let observations = vec![
        reserved(custom_observation(
            1,
            1,
            &local,
            "ingress",
            "{\n\tadmin unix/{{upstreams \"api\"}}\n}",
            [10, 210, 1, 1],
        )),
        staging_web,
        prod_api,
        prod_web,
        staging_other,
    ];
    let admin = FakeAdmin::default();

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIMESTAMP",
        &BTreeMap::new(),
        Some(&admin),
    )
    .await;

    assert!(caddyfile.contains("Service 'ployz-system/ingress': rendering failed:"));
    assert!(caddyfile.contains("Service 'shop-staging/web': rendering failed:"));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'shop-prod/web'.\n\
prod.example { reverse_proxy 10.210.1.11 }"
    ));
    assert!(caddyfile.contains(
        "# User-defined config for Service 'shop-staging/other'.\n\
cross.example { reverse_proxy 10.210.1.11 }"
    ));
    assert!(!caddyfile.contains("staging.example"));
}

#[tokio::test]
async fn unavailable_caddy_omits_every_custom_config() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = [custom_observation(
        1,
        1,
        &local,
        "api",
        "custom.example { respond custom }",
        [10, 210, 1, 1],
    )];

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIME",
        &BTreeMap::new(),
        None::<&FakeAdmin>,
    )
    .await;
    assert!(!caddyfile.contains("custom.example"));
    assert!(caddyfile.contains("admin API is not reachable"));
}

#[tokio::test]
async fn broken_global_template_does_not_hide_valid_service_configs() {
    let local = MachineId::parse("a".repeat(32)).unwrap();
    let observations = [
        reserved(custom_observation(
            1,
            1,
            &local,
            "ingress",
            "{{unknown\ninjected.example { respond owned }\n}}",
            [10, 210, 1, 1],
        )),
        custom_observation(
            2,
            1,
            &local,
            "api",
            "api.example { respond ok }",
            [10, 210, 1, 2],
        ),
    ];

    let caddyfile = generate_caddyfile(
        &local,
        "node-a",
        &service_containers(observations),
        "TIME",
        &BTreeMap::new(),
        Some(&FakeAdmin::default()),
    )
    .await;
    assert!(caddyfile.contains("Service 'ployz-system/ingress': rendering failed"));
    assert!(caddyfile.contains("#   injected.example { respond owned }"));
    assert!(
        !caddyfile
            .lines()
            .any(|line| line.starts_with("injected.example"))
    );
    assert!(caddyfile.contains("api.example { respond ok }"));
}

#[tokio::test]
async fn failed_load_preserves_the_last_caddyfile() {
    let directory =
        std::env::temp_dir().join(format!("ployz-caddy-load-test-{}", std::process::id()));
    let path = directory.join(CONFIG_FILE);
    std::fs::create_dir_all(&directory).unwrap();
    std::fs::write(&path, "last loaded").unwrap();
    let machine = Machine {
        id: MachineId::parse("a".repeat(32)).unwrap(),
        name: MachineName::parse("node-a").unwrap(),
        subnet: "10.210.1.0/24".parse().unwrap(),
        public_key: WireGuardPublicKey([1; 32]),
        public_ip: None,
        advertised_endpoints: vec![AdvertisedEndpoint(
            format!("192.0.2.1:{MACHINE_API_PORT}").parse().unwrap(),
        )],
        runtime: Default::default(),
    };
    let admin = FakeAdmin {
        fail_load: true,
        ..FakeAdmin::default()
    };

    assert!(
        reconcile(&machine, &[], &BTreeMap::new(), &path, Some(&admin),)
            .await
            .is_err()
    );
    assert_eq!(std::fs::read_to_string(&path).unwrap(), "last loaded");
    std::fs::remove_dir_all(directory).unwrap();
}

#[tokio::test]
async fn reconcile_writes_material_and_pins_it_before_load() {
    let directory =
        std::env::temp_dir().join(format!("ployz-caddy-cert-test-{}", std::process::id()));
    let path = directory.join(CONFIG_FILE);
    std::fs::create_dir_all(&directory).unwrap();
    let machine = Machine {
        id: MachineId::parse("a".repeat(32)).unwrap(),
        name: MachineName::parse("node-a").unwrap(),
        subnet: "10.210.1.0/24".parse().unwrap(),
        public_key: WireGuardPublicKey([1; 32]),
        public_ip: None,
        advertised_endpoints: vec![AdvertisedEndpoint(
            format!("192.0.2.1:{MACHINE_API_PORT}").parse().unwrap(),
        )],
        runtime: Default::default(),
    };
    let observations = [observation(
        1,
        &machine.id,
        "api",
        Some([10, 210, 1, 2]),
        vec![ingress("secure.example.com", 8443, HttpProtocol::Https)],
    )];
    let certificates = BTreeMap::from([(
        IngressHost::parse("secure.example.com").unwrap(),
        CertificateRow::from_parts(CertificateMaterial::new("CERT-BODY", "KEY-BODY"), None),
    )]);
    let admin = FakeAdmin::default();
    let certs = directory.join("certs");
    std::fs::create_dir_all(&certs).unwrap();
    let stale_cert = certs.join("secure.example.com-old.crt");
    let stale_key = certs.join("secure.example.com-old.key");
    std::fs::write(&stale_cert, "OLD").unwrap();
    std::fs::write(&stale_key, "OLD").unwrap();

    reconcile(&machine, &observations, &certificates, &path, Some(&admin))
        .await
        .unwrap();

    let caddyfile = std::fs::read_to_string(&path).unwrap();
    let pin = pinned_tls_line(&caddyfile, "secure.example.com").expect("https pin");
    let (cert_name, key_name) = pinned_file_names(pin);
    let cert = certs.join(&cert_name);
    let key = certs.join(&key_name);
    assert_eq!(std::fs::read_to_string(&cert).unwrap(), "CERT-BODY");
    assert_eq!(std::fs::read_to_string(&key).unwrap(), "KEY-BODY");
    assert_eq!(
        std::fs::metadata(&key).unwrap().permissions().mode() & 0o777,
        0o600
    );
    assert!(!stale_cert.exists());
    assert!(!stale_key.exists());
    let adapted = admin.adapted.lock().unwrap();
    assert!(
        adapted
            .last()
            .is_some_and(|config| config.contains(&format!("tls /config/caddy/certs/{cert_name}")))
    );
    std::fs::remove_dir_all(directory).unwrap();
}

fn pinned_tls_line<'a>(caddyfile: &'a str, hostname: &str) -> Option<&'a str> {
    let needle = format!("tls /config/caddy/certs/{hostname}-");
    caddyfile.lines().find(|line| line.contains(&needle))
}

fn pinned_file_names(pin: &str) -> (String, String) {
    let mut paths = pin.split_whitespace().skip(1);
    let cert = paths.next().expect("cert path");
    let key = paths.next().expect("key path");
    (
        Path::new(cert)
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .to_owned(),
        Path::new(key)
            .file_name()
            .unwrap()
            .to_str()
            .unwrap()
            .to_owned(),
    )
}

#[derive(Default)]
struct FakeAdmin {
    adapted: Mutex<Vec<String>>,
    fail_load: bool,
}

impl CaddyAdmin for FakeAdmin {
    async fn adapt(&self, caddyfile: &str) -> Result<String, Error> {
        self.adapted.lock().unwrap().push(caddyfile.into());
        if caddyfile.contains("# invalid") {
            Err(Error::Admin("invalid config detected".into()))
        } else {
            Ok("{}".into())
        }
    }

    async fn load(&self, _json: &str) -> Result<(), Error> {
        if self.fail_load {
            Err(Error::Admin("load failed".into()))
        } else {
            Ok(())
        }
    }
}

fn ingress(hostname: &str, port: u16, http_protocol: HttpProtocol) -> PortPublication {
    PortPublication::Ingress {
        hostname: IngressHostname::explicit(hostname).unwrap(),
        load_balancer_port: port.try_into().unwrap(),
        container_port: port.try_into().unwrap(),
        http_protocol,
    }
}

fn reserved(mut observation: ContainerObservation) -> ContainerObservation {
    observation
        .try_update(|parts| parts.project_name = ployz_core::ProjectName::system())
        .unwrap();
    observation
}

fn observation(
    suffix: u8,
    machine_id: &MachineId,
    service_name: &str,
    address: Option<[u8; 4]>,
    ports: Vec<PortPublication>,
) -> ContainerObservation {
    let service_id = ServiceId::parse(format!("{suffix:x}").repeat(32)).unwrap();
    let service_name = ServiceName::parse(service_name).unwrap();
    let resolved_spec: ResolvedServiceSpec = serde_json::from_value(json!({
        "service_id": service_id,
        "name": service_name,
        "mode": { "mode": "replicated", "replicas": 1 },
        "container": { "image": "example.test/image", "pull_policy": "missing" },
        "ports": ports,
    }))
    .unwrap();
    ployz_core::ContainerObservation::try_from(ployz_core::ContainerObservationParts {
        container_id: ContainerId::parse(format!("{suffix:x}").repeat(64)).unwrap(),
        display_name: format!("{service_name}-{suffix}"),
        created_at_unix_nanos: 0,
        machine_id: *machine_id,
        project_name: ployz_core::ProjectName::parse("app").unwrap(),
        kind: ContainerKind::ServiceContainer,
        runtime: ContainerRuntimeObservation::Running {
            health: HealthObservation::Healthy,
        },
        effective_healthcheck: None,
        resolved_spec,
        address: address.map(|address| ContainerAddress(address.into())),
        labels: BTreeMap::new(),
    })
    .unwrap()
}

fn custom_observation(
    suffix: u8,
    created_at_unix_nanos: i64,
    machine_id: &MachineId,
    service_name: &str,
    caddy_config: &str,
    address: [u8; 4],
) -> ContainerObservation {
    let mut observation = observation(suffix, machine_id, service_name, Some(address), Vec::new());
    observation
        .try_update(|parts| parts.created_at_unix_nanos = created_at_unix_nanos)
        .unwrap();
    observation
        .try_update(|parts| {
            parts.resolved_spec.ingress_proxy_fragment =
                Some(IngressProxyFragment::parse_caddy(caddy_config).expect("fixture is non-empty"))
        })
        .unwrap();
    observation
}
